<?php

global $CronConfigs;

$CronConfigs["actionautochryslerdodgejeep"] = array(
    'password'         => 'actionautochryslerdodgejeep',
    'email'            => 'regan@smedia.ca',
    'log'              => true,
    'fb_brand'         => '[year] [make] [model] - [body_style]',
    'banner'           => array(
        'template'                   => 'actionautochryslerdodgejeep',
        'fb_description'             => 'Are you still interested in the [year] [make] [model]? Click for more info.',
        'fb_lookalike_description'   => 'Check out this [year] [make] [model]! Click for more information.',
        'fb_marketplace_description' => '[description]',
        'flash_style'                => 'default',
        'border_color'               => '#282828',
        'styels'                     => array(
            'new_display'       => 'custom_banner',
            'used_display'      => 'custom_banner',
            'new_retargeting'   => 'custom_banner',
            'used_retargeting'  => 'custom_banner',
            'new_marketbuyers'  => 'custom_banner',
            'used_marketbuyers' => 'custom_banner',
        ),
        'font_color'                 => '#ffffff',
    ),
    'lead'             => array(
        'live'                   => false,
        'lead_type_'             => true,
        'lead_type_new'          => true,
        'lead_type_used'         => true,
        'lead_type_service'      => true,
        'shown_cap'              => false,
        'fillup_cap'             => false,
        'session_close'          => false,
        'device_type'            => array(
            'mobile'  => true,
            'desktop' => true,
            'tablet'  => true,
        ),
        'offer_minimum_price'    => 1500,
        'offer_maximum_price'    => 10000000,
        'bg_color'               => '#162433',
        'text_color'             => '#FFFFFF',
        'border_color'           => '#AE2419',
        'button_color'           => array(
            '#AE2419',
            '#AE2419',
        ),
        'button_color_hover'     => array(
            '#950B00',
            '#950B00',
        ),
        'button_color_active'    => array(
            '#950B00',
            '#950B00',
        ),
        'button_text_color'      => '#FFFFFF',
        'response_email_subject' => '$250 trade in coupon from action auto chrysler dodge jeep',
        'response_email'         => 'Hello [name],<p> Thank you for signing up for our offer!  Please print this off or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>action auto chrysler dodge jeep',
        'forward_to'             => array(
            'info@heartlandhonda.com',
            'marshal@smedia.ca',
        ),
        'special_to'             => array(),
        'special_email'          => '',
        'display_after'          => 5000,
        'retarget_after'         => 5000,
        'fb_retarget_after'      => 5000,
        'adword_retarget_after'  => 5000,
        'visit_count'            => 0,
        'video_smart_offer'      => false,
        'video_smart_offer_form' => true,
        'video_url'              => '',
        'video_title'            => '',
        'video_description'      => '',
        'lead_in'                => array(
            'vdp'           => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
            'service_regex' => '',
        ),
    ),
    'mail_retargeting' => array(
        'enabled'             => null,
        'client_id'           => '',
        'promotion_text'      => '',
        'promotion_color'     => '#567DC0',
        'overlay_color'       => '#FF8500',
        'overlay_text_colour' => '#FFFFFF',
        'price_color'         => '#FF8500',
        'coupon_validity'     => '8',
    ),
    'name'             => 'actionautochryslerdodgejeep',
);