<?php

global $CronConfigs;
$CronConfigs["barrycullen"] = array(
    'password' => 'barrycullen',
    "email" => "regan@smedia.ca",
    'fb_brand' => '[year] [make] [model] - [body_style]',
    'log' => true,
    'max_cost' => 500,
    'cost_distribution' => array(
        'new' => 200,
        'used' => 100,
        'brand' => 200,
),
    "create" => array(
        "new_search" => yes,
        "used_search" => yes,
        "new_placement" => no,
        "used_placement" => no,
        "new_display" => no,
        "used_display" => no,
        "new_retargeting" => yes,
        "used_retargeting" => no,
        "new_marketbuyers" => no,
        "used_marketbuyers" => no,
        "new_combined" => no,
        "used_combined" => no,
),
    "new_descs" => array(
        array(
            "desc1" => "Test Drive the [year]",
            "desc2" => "[make] [model] today.",
),
        array(
            "desc1" => "Call us today about the ",
            "desc2" => "[year] [make] [model] today",
),
),
    "used_descs" => array(
        array(
            "desc1" => "Test Drive the [year]",
            "desc2" => "[make] [model] today.",
),
        array(
            "desc1" => "Call us today about the ",
            "desc2" => "[year] [make] [model] today",
),
),
    'customer_id' => '922-323-8795',
    "lead" => array(
        'live' => false,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#151419',
            '#151419',
),
        'button_color_hover' => array(
            '#E1A504',
            '#E1A504',
),
        'button_color_active' => array(
            '#E1A504',
            '#E1A504',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => 'Get $200 off with this offer from Barry Cullen',
        'response_email' => 'Hello [name],<p> Thank you for booking a test drive! Please print this off or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Barry Cullen',
        'forward_to' => array(
            'hinoonchev@hotmail.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/VehicleDetails\\/(?:new|used|certified)-[0-9]{4}-\\S+/i',
            'service' => '',
),
),
    'fb_brand' => '[year] [make] [model] - [body_style]',
    "banner" => array(
        "template" => "barrycullen",
        "fb_description" => "Are you still interested in the [year] [make] [model] [trim]? We're still here for you online!",
        //	"fb_description" => "Get Black Friday prices until December 2nd on most new inventory! Save up to $7000 off MSRP cash purchase price, or get 0% financing up to 72 months PLUS get a $750 Black Friday Bonus on select new vehicles! *excludes Spark, Cruze, Malibu, Bolt, Volt, Trax and XT4.",
        "fb_lookalike_description" => "Check out this [year] [make] [model] [trim] - We're still here for you online!",
        //"fb_dynamiclead_description" => "Are you still interested in the [year] [make] [model]? Click below, fill in your info to get \$200 OFF, and a product specialist will be in touch to aid in any questions.",
        "fb_marketplace_description" => "[description]",
        "flash_style" => "default",
        "styels" => array(
            "new_display" => "dynamic_banner",
            "used_display" => "dynamic_banner",
            "new_retargeting" => "dynamic_banner",
            "used_retargeting" => "dynamic_banner",
            "new_marketbuyers" => "dynamic_banner",
            "used_marketbuyers" => "dynamic_banner",
),
        "border_color" => "#282828",
        "hst" => yes,
        "font_color" => "#ffffff",
),
);