<?php

global $CronConfigs;

$CronConfigs["campkins"] = array(
    'bid'               => 3.0,
    'password'          => 'campkins',
    'post_code'         => 'L0B 1A0',
    'log'               => true,
    'customer_id'       => '136-113-8695',
    'email'             => 'regan@smedia.ca',
    'fb_brand'          => '[year] [make] [model] - [body_style]',
    'banner'            => array(
        'template'                   => 'campkins',
        'flash_style'                => 'default',
        'fb_description'             => 'Are you still interested in the [make] [model]? Click for more info.',
        'fb_lookalike_description'   => 'Check out the [make] [model] today! Click for details.',
        'fb_dynamiclead_description' => 'Are you still interested in the [make] [model]? Click below, fill in your info to get an additional $100 store credit, and a product specialist will be in touch to aid in any questions',
        'border_color'               => '#282828',
        'styels'                     => array(
            'new_display'       => 'custom_banner',
            'used_display'      => 'custom_banner',
            'new_retargeting'   => 'custom_banner',
            'used_retargeting'  => 'custom_banner',
            'new_marketbuyers'  => 'custom_banner',
            'used_marketbuyers' => 'custom_banner',
        ),
        'font_color'                 => '#ffffff',
    ),
    'lead'              => array(
        'new' => array(
            'live'                   => true,
            'lead_type_'             => true,
            'lead_type_new'          => true,
            'lead_type_used'         => false,
            'lead_type_service'      => false,
            'shown_cap'              => true,
            'fillup_cap'             => true,
            'session_close'          => false,
            'device_type'            => array(
                'mobile'  => true,
                'desktop' => true,
                'tablet'  => true,
            ),
            'sent_client_email'      => true,
            'offer_minimum_price'    => 0,
            'offer_maximum_price'    => 10000000,
            'bg_color'               => '#EFEFEF',
            'text_color'             => '#404450',
            'border_color'           => '#E5E5E5',
            'button_color'           => array(
                '#FB5523',
                '#FB5523',
            ),
            'button_color_hover'     => array(
                '#FF7036',
                '#FF7036',
            ),
            'button_color_active'    => array(
                '#FB5523',
                '#FB5523',
            ),
            'button_text_color'      => '#FFFFFF',
            'response_email_subject' => 'Your offer from Campkin\'s RV Centre',
            'response_email'         => 'Hello [name],<p> Thanks for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Campkin\'s Team',
            'forward_to'             => array(
                'sales@campkins.com',
                'marshal@smedia.ca',
            ),
            'special_to'             => array(
                '',
            ),
            'special_email'          => '',
            'display_after'          => 30000,
            'retarget_after'         => 5000,
            'fb_retarget_after'      => 5000,
            'adword_retarget_after'  => 5000,
            'visit_count'            => 0,
            'video_smart_offer'      => false,
            'video_smart_offer_form' => false,
            'video_url'              => '',
            'video_title'            => '',
            'video_description'      => '',
            'lead_in'                => array(
                'vdp'           => '/\\/rv-inventory\\/(?:new|used)\\/[^\\/]+\\/[0-9]{4}-/i',
                'service_regex' => '',
            ),
            'custom_div'             => '',
        ),
    ),
    'max_cost'          => 250,
    'cost_distribution' => array(),
    'name'              => 'campkins',
);
