<?php

global $CronConfigs;
$CronConfigs["cumberlandtoyota"] = array(
    "name" => "cumberlandtoyota",
    "email" => "regan@smedia.ca",
    "password" => "cumberlandtoyota",
    "log" => true,
	
	"banner" => array(
        "template" => "cumberlandtoyota",
		"fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
		"fb_lookalike_description"	=> "Check out this [year] [make] [model] today! Click for more information.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff"
    ),
	
    'buttons_live' => true,
    'buttons' => [
        'request-a-quote' => [
            'url-match' => '/\\/vehicle-details\\/new-[0-9]/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.vdp-vehicle-pricing-toolbar div.column center a',
            'css-class' => 'div.vdp-vehicle-pricing-toolbar div.column center a',
            'css-hover' => 'div.vdp-vehicle-pricing-toolbar div.column center a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'div.vdp-vehicle-pricing-toolbar div.column center a',
                    'values' => array(
                        'Request A Quote',
                        'Get E Price Now!',
                        'Get your Price!',
                        'E-Price',
                        'Get Our Best Price',
                        'Special Pricing!',
                        'Get Special Price!',
                        'Special Pricing!',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'financing' => [
            'url-match' => '/\\/vehicle-details\\/(?:new|used)-[0-9]{4}/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.column.text-center span',
            'css-class' => 'div.column.text-center span',
            'css-hover' => 'div.column.text-center span:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'financing' => [
                    'target' => 'div.column.text-center span',
                    'values' => array(
                        'Special Finance Offers!',
                        'Explore Payments',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'request-information' => [
            'url-match' => '/\\/vehicle-details\\/used-[0-9]{4}/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.row.small-up-1.medium-up-1.large-up-1 div.column > center a',
            'css-class' => 'div.row.small-up-1.medium-up-1.large-up-1 div.column > center a',
            'css-hover' => 'div.row.small-up-1.medium-up-1.large-up-1 div.column > center a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'request-information' => [
                    'target' => 'div.row.small-up-1.medium-up-1.large-up-1 div.column > center a',
                    'values' => array(
                        'Check Availability',
                        'Get Availability',
                        'Ask For Availability',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Listing request-a-quote' => [
            'url-match' => '/\\/new-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.medium-6.medium-push-6.columns > center:nth-of-type(1) a',
            'css-class' => 'div.medium-6.medium-push-6.columns > center:nth-of-type(1) a',
            'css-hover' => 'div.medium-6.medium-push-6.columns > center:nth-of-type(1) a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'div.medium-6.medium-push-6.columns > center:nth-of-type(1) a',
                    'values' => array(
                        'Get E Price Now!',
                        'Get your Price!',
                        'Get Our Best Price',
                        'Special Pricing!',
                        'Get Special Price!',
                        'Special Pricing!',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Used Listing request-information' => [
            'url-match' => '/\\/used-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.medium-6.medium-push-6.columns > center >center > a',
            'css-class' => 'div.medium-6.medium-push-6.columns > center >center > a',
            'css-hover' => 'div.medium-6.medium-push-6.columns > center >center > a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'request-information' => [
                    'target' => 'div.medium-6.medium-push-6.columns > center >center > a',
                    'values' => array(
                        'Check Availability',
                        'Get Availability',
                        'Ask For Availability',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Listing financing' => [
            'url-match' => '/\\/(?:new|used)-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.medium-6.medium-push-6.columns > center > span a',
            'css-class' => 'div.medium-6.medium-push-6.columns > center > span a',
            'css-hover' => 'div.medium-6.medium-push-6.columns > center > span a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'financing' => [
                    'target' => 'div.medium-6.medium-push-6.columns > center > span a',
                    'values' => array(
                        'Special Finance Offers!',
                        'Explore Payments',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
    ],
);