<?php

global $CronConfigs;
$CronConfigs["cumberland_auto"] = array(
    "name" => "cumberland_auto",
    "email" => "regan@smedia.ca",
    "password" => "cumberland-auto",
    "log" => true,
    'buttons_live' => true,
    'buttons' => [
        'calculate-payment' => [
            'url-match' => '/\\/vehicle-details\\/(?:new|used)-[0-9]{4}/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(2) span a',
            'css-class' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(2) span a',
            'css-hover' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(2) span a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'calculate-payment' => [
                    'target' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(2) span a',
                    'values' => array(
                        'Special Finance Offers!',
                        'Explore Payments',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'request-information' => [
            'url-match' => '/\\/vehicle-details\\/used-[0-9]{4}/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a',
            'css-class' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a',
            'css-hover' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                ' request-information' => [
                    'target' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a',
                    'values' => array(
                        'Check Availability',
                        'Get Availability',
                        'Ask For Availability',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'request-a-quote' => [
            'url-match' => '/\\/vehicle-details\\/new-[0-9]{4}/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a',
            'css-class' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a',
            'css-hover' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                ' request-information' => [
                    'target' => 'div.row.small-up-1.medium-up-1.large-up-1 div:nth-of-type(1) center a',
                    'values' => array(
                        'Request A Quote',
                        'Get E Price Now!',
                        'Get your Price!',
                        'E-Price',
                        'Get Our Best Price',
                        'Special Pricing!',
                        'Get Special Price!',
                        'Special Pricing!',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Listing request-a-quote' => [
            'url-match' => '/\\/(?:new|inventory)/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.medium-6.medium-push-6.columns center  a[onclick*=BestPrice]',
            'css-class' => 'div.medium-6.medium-push-6.columns center  a[onclick*=BestPrice]',
            'css-hover' => 'div.medium-6.medium-push-6.columns center  a[onclick*=BestPrice]:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                ' request-information' => [
                    'target' => 'div.medium-6.medium-push-6.columns center  a[onclick*=BestPrice]',
                    'values' => array(
                        'Request A Quote',
                        'Get E Price Now!',
                        'Get your Price!',
                        'E-Price',
                        'Get Our Best Price',
                        'Special Pricing!',
                        'Get Special Price!',
                        'Special Pricing!',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Listing calculate-payment' => [
            //new listing
            'url-match' => '/\\/(?:new|inventory)/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'a[name=AutoAPRLinkPlaceholder]',
            'css-class' => 'a[name="AutoAPRLinkPlaceholder"]',
            'css-hover' => 'a[name="AutoAPRLinkPlaceholder"]:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'calculate-payment' => [
                    'target' => 'a[name=AutoAPRLinkPlaceholder]',
                    'values' => array(
                        'Special Finance Offers!',
                        'Explore Payments',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Listing request-information' => [
            //used listing
            'url-match' => '/\\/(?:used|inventory)/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'div.medium-6.medium-push-6 center a[href*=openModal]',
            'css-class' => 'div.medium-6.medium-push-6 center a[href*=openModal]',
            'css-hover' => 'div.medium-6.medium-push-6 center a[href*=openModal]:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                ' request-information' => [
                    'target' => 'div.medium-6.medium-push-6 center a[href*=openModal]',
                    'values' => array(
                        'Check Availability',
                        'Get Availability',
                        'Ask For Availability',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'Used Listing calculate-payment' => [
            'url-match' => '/\\/(?:used|inventory)/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'a[name=AutoAPRLinkPlaceholder]',
            'css-class' => 'a[name="AutoAPRLinkPlaceholder"]',
            'css-hover' => 'a[name="AutoAPRLinkPlaceholder"]:hover',
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'calculate-payment' => [
                    'target' => 'a[name=AutoAPRLinkPlaceholder]',
                    'values' => array(
                        'Special Finance Offers!',
                        'Explore Payments',
                    ),
                ],
            ],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E1AD01,#E1AD01)',
                        'border-color' => '#f06b20',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#BC9104,#BC9104)',
                        'border-color' => '#cf540e',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E40E0D,#E40E0D)',
                        'border-color' => '#e01212',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D00D0C,#D00D0C)',
                        'border-color' => '#c60c0d',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#31A413,#31A413)',
                        'border-color' => '#54b740',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#23810B,#23810B)',
                        'border-color' => '#359d22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#1F89CA,#1F89CA)',
                        'border-color' => '#1ca0d1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#1A7DB9,#1A7DB9)',
                        'border-color' => '#188bb7',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 10px',
                        'padding' => '12px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
    ],
);