<?php

global $CronConfigs;
$CronConfigs["dougmarshallgmcom"] = array(
    'name' => 'dougmarshallgmcom',
    'email' => 'regan@smedia.ca',
    'password' => 'dougmarshallgmcom',
    'log' => true,
    'customer_id' => '411-852-6217',
    'combined_feed_mode' => true,
    'banner' => array(
        'template' => 'dougmarshallgmcom',
        'fb_description' => 'Are you still interested in the [year] [make] [model]? Click for more info!',
        'fb_lookalike_description' => 'Check out this [year] [make] [model] today! Click for more information.',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => '#ffffff',
),
    'lead' => array(
        'live' => false,
        'lead_type_' => false,
        'lead_type_new' => false,
        'lead_type_used' => false,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'sent_client_email' => true,
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#072E61',
            '#072E61',
),
        'button_color_hover' => array(
            '#041731',
            '#041731',
),
        'button_color_active' => array(
            '#041731',
            '#041731',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => '$200 off coupon from Doug Marshall GM',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Doug Marshall GM Team',
        'forward_to' => array(
            'leads@dougmarshallgm.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/inventory\\/(?:new|used|certified)-[0-9]{4}-/',
            'service_regex' => '',
),
        'custom_div' => '',
),
    'max_cost' => 640,
    'cost_distribution' => array(
        'new' => 240,
        'used' => 400,
),
    'adf_to' => array(
        0 => '',
),
    'form_live' => false,
    'buttons_live' => false,
);