<?php

global $CronConfigs;
$CronConfigs["easternchrysler"] = array(
    'name' => 'easternchrysler',
    'email' => 'regan@smedia.ca',
    'password' => 'easternchrysler',
    'log' => true,
    'banner' => array(
        'template' => 'easternchrysler',
        'fb_description' => 'Are you still interested in the [year] [make] [model]? Click for more info.',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => '#ffffff',
),
    'lead' => array(
        'new' => array(
            'live' => true,
            'lead_type_' => true,
            'lead_type_new' => true,
            'lead_type_used' => true,
            'lead_type_service' => false,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 0,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#404450',
            'border_color' => '#E5E5E5',
            'button_color' => array(
                '#BD1F1B',
                '#BD1F1B',
),
            'button_color_hover' => array(
                '#A90B07',
                '#A90B07',
),
            'button_color_active' => array(
                '#D83A36',
                '#D83A36',
),
            'button_text_color' => '#FFFFFF',
            'response_email_subject' => 'Claim $500 Off with purchase from Eastern CDJR',
            'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Eastern CDJR Team',
            'forward_to' => array(
                '',
),
            'special_to' => array(
                'leads@easterncdj.motosnap.com',
),
            'special_email' => '',
            'display_after' => 20000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '/\\/vehicles\\/[0-9]{4}\\//',
                'service_regex' => '',
),
            'custom_div' => '',
),
        'used' => array(
            'live' => true,
            'lead_type_' => true,
            'lead_type_new' => false,
            'lead_type_used' => true,
            'lead_type_service' => false,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'inactivity' => true,
            'exit_intent' => true,
            'session_depth' => false,
            'campaign_cap_google' => false,
            'campaign_cap_fb' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 0,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#FFFFFF',
            'border_color' => '#FFFFFF',
            'button_color' => array(
                '#FFFFFF',
                '#FFFFFF',
),
            'button_color_hover' => array(
                '#FFFFFF',
                '#FFFFFF',
),
            'button_color_active' => array(
                '#FFFFFF',
                '#FFFFFF',
),
            'button_text_color' => '#FFFFFF',
            'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject' => '',
            'response_email' => '',
            'forward_to' => array(
                '',
),
            'special_to' => array(
                '',
),
            'special_email' => '',
            'display_after' => 20000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'shown_cap_count' => 1,
            'fillup_cap_time_days' => 7,
            'session_close_cap' => 3,
            'inactivity_timeout' => 600000,
            'exit_intent_timeout' => 10000,
            'session_depth_page' => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days' => 7,
            'campaign_fb_cap_count' => 3,
            'campaign_fb_cap_days' => 7,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '/\\/vehicles\\/[0-9]{4}\\//',
                'service_regex' => '',
),
            'custom_div' => '',
            'provider_name' => 'sMedia',
            'source' => 'sMedia smartoffer',
),
),
);