<?php

global $CronConfigs;
$CronConfigs["eliteautocentre"] = array(
    'name' => 'eliteautocentre',
    'email' => 'regan@smedia.ca',
    'fb_brand' => '[year] [make] [model] - [body_style]',
    'password' => 'eliteautocentre',
    'log' => true,
    'customer_id' => '526-836-8356',
    'max_cost' => 460,
    'cost_distribution' => 
    array (
      'adwords' => 460,
    ),
    'fb_title' => '[year] [make] [model] [price]',
    'banner' => array(
        'template' => 'eliteautocentre',
        'fb_description' => 'Are you still interested in the [year] [make] [model]? Click for more info!',
        'fb_aia_description' => '[description]. Check out this [year] [make] [model] today! Click the \'Dealership Website\' link below for more information.',
        'fb_lookalike_description' => 'Check out this [year] [make] [model] today! Click for more info!',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => 'ffffff',
        'fb_marketplace_description' => '[year] [make] [model] Check it out today!',
),
    'lead' => array(
        'live' => false,
        'lead_type_' => false,
        'lead_type_new' => false,
        'lead_type_used' => false,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'inactivity' => true,
        'exit_intent' => true,
        'session_depth' => false,
        'campaign_cap_google' => false,
        'campaign_cap_fb' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'sent_client_email' => true,
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#AA1B1B',
            '#AA1B1B',
),
        'button_color_hover' => array(
            '#313131',
            '#313131',
),
        'button_color_active' => array(
            '#313131',
            '#313131',
),
        'button_text_color' => '#FFFFFF',
        'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
        'response_email_subject' => 'At Elite Auto Centre we\'ll help you get approved!',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Elite Auto Centre Team',
        'forward_to' => array(
            'bert@eliteautocentre.ca',
            'kyra@eliteautocentre.ca',
            'kent@eliteautocentre.ca',
            'mdm@eliteautocentre.ca',
            'mark@eliteautocentre.ca',
            'Sales@eliteautocentre.ca',
            'marshal@smedia.ca',
            'ggaspari@shawcable.com',
            'kyle@eliteautocentre.ca',
            'tamissy13@gmail.com',
            'steve@eliteautocentre.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'shown_cap_count' => 1,
        'fillup_cap_time_days' => 7,
        'session_close_cap' => 3,
        'inactivity_timeout' => 600000,
        'exit_intent_timeout' => 10000,
        'session_depth_page' => 0,
        'campaign_google_cap_count' => 3,
        'campaign_google_cap_days' => 7,
        'campaign_fb_cap_count' => 3,
        'campaign_fb_cap_days' => 7,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/[0-9]{4}-[^\\~]+\\~/i',
            'service_regex' => '',
),
        'custom_div' => '',
        'provider_name' => 'sMedia',
        'source' => 'sMedia smartoffer',
),
);