<?php

global $CronConfigs;
$CronConfigs["erinmillsmazda"] = array(
    'name' => 'erinmillsmazda',
    'email' => 'regan@smedia.ca',
    'password' => 'erinmillsmazda',
    'log' => true,
    'customer_id' => '954-929-6462',
    'max_cost' => 870,
    'cost_distribution' => array(
        'adwords' => 870,
),
    'combined_feed_mode' => true,
    'banner' => array(
        'template' => 'erinmillsmazda',
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today! Click for more information.",
        'fb_aia_description' => '[description]. Check out this [year] [make] [model] today! Click the \'Dealership Website\' link below for more information.',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => '#ffffff',
),
    'lead' => array(
        'service' => array(
            'live' => true,
            'lead_type_' => false,
            'lead_type_new' => false,
            'lead_type_used' => false,
            'lead_type_service' => true,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'inactivity' => true,
            'exit_intent' => true,
            'session_depth' => false,
            'campaign_cap_google' => false,
            'campaign_cap_fb' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 0,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#404450',
            'border_color' => '#E5E5E5',
            'button_color' => array(
                '#101010',
                '#101010',
),
            'button_color_hover' => array(
                '#910A2D',
                '#910A2D',
),
            'button_color_active' => array(
                '#910A2D',
                '#910A2D',
),
            'button_text_color' => '#FFFFFF',
            'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject' => 'Save up to $120.00 on new winter tires at [dealership]',
            'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Erin Mills Mazda Team',
            'forward_to' => array(),
            'special_to' => array(
                'service@erinmillsmazda.com',
),
            'special_email' => '',
            'display_after' => 30000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'shown_cap_count' => 1,
            'fillup_cap_time_days' => 7,
            'session_close_cap' => 3,
            'inactivity_timeout' => 600000,
            'exit_intent_timeout' => 10000,
            'session_depth_page' => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days' => 7,
            'campaign_fb_cap_count' => 3,
            'campaign_fb_cap_days' => 7,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '',
                'service_regex' => '/\\/(?:service|parts|mazda)/i',
),
            'custom_div' => '',
            'provider_name' => 'sMedia',
            'source' => 'sMedia smartoffer',
),
        'new' => array(
            'live' => true,
            'lead_type_' => true,
            'lead_type_new' => true,
            'lead_type_used' => false,
            'lead_type_service' => false,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'inactivity' => true,
            'exit_intent' => true,
            'session_depth' => false,
            'campaign_cap_google' => false,
            'campaign_cap_fb' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 0,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#404450',
            'border_color' => '#E5E5E5',
            'button_color' => array(
                '#101010',
                '#101010',
),
            'button_color_hover' => array(
                '#910A2D',
                '#910A2D',
),
            'button_color_active' => array(
                '#910A2D',
                '#910A2D',
),
            'button_text_color' => '#FFFFFF',
            'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject' => 'Get $300 off coupon from Erin Mills Mazda',
            'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Erin Mills Mazda Team',
            'forward_to' => array(
                'a_soos@erinmillsmazda.com',
                'n_kent@erinmillsmazda.com',
                'z_dossani@erinmillsmazda.com',
                'a_sheikh@erinmillsmazda.com',
                'a_soos@erinmillsmazda.com',
),
            'special_to' => array(),
            'special_email' => '',
            'display_after' => 30000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'shown_cap_count' => 1,
            'fillup_cap_time_days' => 7,
            'session_close_cap' => 3,
            'inactivity_timeout' => 600000,
            'exit_intent_timeout' => 10000,
            'session_depth_page' => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days' => 7,
            'campaign_fb_cap_count' => 3,
            'campaign_fb_cap_days' => 7,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '/\\/(?:new|used)\\/vehicle\\/[0-9]{4}-/i',
                'service_regex' => '',
),
            'custom_div' => '',
            'provider_name' => 'sMedia',
            'source' => 'sMedia smartoffer',
),
        'used' => array(
            'live' => true,
            'lead_type_' => true,
            'lead_type_new' => false,
            'lead_type_used' => true,
            'lead_type_service' => false,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'inactivity' => true,
            'exit_intent' => true,
            'session_depth' => false,
            'campaign_cap_google' => false,
            'campaign_cap_fb' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 0,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#404450',
            'border_color' => '#E5E5E5',
            'button_color' => array(
                '#101010',
                '#101010',
),
            'button_color_hover' => array(
                '#910A2D',
                '#910A2D',
),
            'button_color_active' => array(
                '#910A2D',
                '#910A2D',
),
            'button_text_color' => '#FFFFFF',
            'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject' => 'Get $300 off coupon from Erin Mills Mazda',
            'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Erin Mills Mazda Team',
            'forward_to' => array(
                'a_soos@erinmillsmazda.com',
                'n_kent@erinmillsmazda.com',
                'z_dossani@erinmillsmazda.com',
                'a_sheikh@erinmillsmazda.com',
                'a_soos@erinmillsmazda.com',
),
            'special_to' => array(),
            'special_email' => '',
            'display_after' => 30000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'shown_cap_count' => 1,
            'fillup_cap_time_days' => 7,
            'session_close_cap' => 3,
            'inactivity_timeout' => 600000,
            'exit_intent_timeout' => 10000,
            'session_depth_page' => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days' => 7,
            'campaign_fb_cap_count' => 3,
            'campaign_fb_cap_days' => 7,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '/\\/(?:new|used)\\/vehicle\\/[0-9]{4}-/i',
                'service_regex' => '',
),
            'custom_div' => '',
            'provider_name' => 'sMedia',
            'source' => 'sMedia smartoffer',
),
),
    'smart_memo' => array(
        'live' => true,
        'live_new' => false,
        'live_used' => false,
        'live_home' => true,
        'live_service' => false,
        'video' => false,
        'hide_redirection' => false,
        'video_url' => '',
        'button_text' => 'learn more',
        'url' => 'https://www.erinmillsmazda.ca/contact/',
        'home_url' => 'https://www.erinmillsmazda.ca/',
        'service_regex' => '',
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_text_color' => '#FFFFFF',
        'button_color' => array(
            '#000000',
            '#000000',
),
        'button_color_hover' => array(
            '#222222',
            '#222222',
),
        'button_color_active' => array(
            '#222222',
            '#222222',
),
),
);