<?php

global $CronConfigs;
$CronConfigs["farmworld"] = array(
    "name" => "farmworld",
    "email" => "regan@smedia.ca",
    "password" => "farmworld",
    'fb_brand' => '[year] [make] [model] - [body_style]',
    'fb_title' => "[year] [make] [model]",
    "log" => true,
    // 'no_adv' => true,
    'customer_id' => '279-855-3446',
    'max_cost' => 975,
    'cost_distribution' => array(
        'new' => 0,
        'used' => 975,
),
    "create" => array(
        "new_search" => yes,
        "used_search" => yes,
),
    // 'title' => "[title]",
    //   'title2'        => "Get More Info Now",
    "new_descs" => array(
        [
            /* Other supported fields in description configuration */
            'title2' => 'Inquire For Price',
            'title3' => 'Get More Info Now',
            'description' => 'Call us today about the [make] [model] today',
            'description2' => 'Contact Farm World Today!',
],
        [
            /* Other supported fields in description configuration */
            'title2' => 'Inquire For Price',
            'title3' => 'Get More Info Now',
            'description' => 'Get More Information About the [make] [model] today.',
            'description2' => 'Contact Farm World Today!',
],
),
    "used_descs" => array(
        [
            /* Other supported fields in description configuration */
            'title2' => 'Inquire For Price',
            'title3' => 'Get More Info Now',
            'description' => 'Call us today about the [make] [model] today',
            'description2' => 'Contact Farm World Today!',
],
        [
            /* Other supported fields in description configuration */
            'title2' => 'Inquire For Price',
            'title3' => 'Get More Info Now',
            'description' => 'Get More Information About the [make] [model] today.',
            'description2' => 'Contact Farm World Today!',
],
),
    "banner" => array(
        "template" => "farmworld",
        'fb_description' => "Are you still interested in the [title]? Click for more information.",
        'fb_aia_description' => '[description]. Check out this [year] [make] [model] today! Click the \'Dealership Website\' link below for more information.',
        'fb_lookalike_description' => "Check out this [title] today! Click for more information.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "styels" => array(
            "new_display" => "dynamic_banner",
            "used_display" => "dynamic_banner",
            "new_retargeting" => "dynamic_banner",
            "used_retargeting" => "dynamic_banner",
            "new_marketbuyers" => "dynamic_banner",
            "used_marketbuyers" => "dynamic_banner",
),
        "font_color" => "#ffffff",
),
    'adf_to' => array(
        'cbauer@farmworld.ca',
),
    'form_live' => true,
    'buttons_live' => true,
    'buttons' => [
        'request-information' => [
            'url-match' => '/\\/is-equipment-listings\\/view\\/[0-9]+-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'ul.no-bullets li:nth-of-type(1)',
            'css-class' => 'ul.no-bullets li:nth-of-type(1)',
            'css-hover' => 'ul.no-bullets li:nth-of-type(1):hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-information' => [
                    'target' => 'ul.no-bullets li:nth-of-type(1)',
                    'values' => array(
                        'Get More Information',
                        'Ask a Question',
                        'Request More Info',
                        'Contact Us For More Info',
),
],
],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#F4890A,#F4890A)',
                        'border-color' => 'F4890A',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#DA7B09,#DA7B09)',
                        'border-color' => 'DA7B09',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E21F26,#E21F26)',
                        'border-color' => 'E21F26',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#C81C22,#C81C22)',
                        'border-color' => 'C81C22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#57B947,#57B947)',
                        'border-color' => '57B947',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#489F46,#489F46)',
                        'border-color' => '489F46',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#007EBF,#007EBF)',
                        'border-color' => '007EBF',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#006DA5,#006DA5)',
                        'border-color' => '006DA5',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'form-submit' => [
            'url-match' => '/\\/is-equipment-listings\\/view\\/[0-9]+-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'div.form-group button',
            'css-class' => 'div.form-group button',
            'css-hover' => 'div.form-group button:hover',
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'form-submit' => [
                    'target' => 'div.form-group button',
                    'values' => array(
                        'Send Message',
                        'Submit Now',
                        'Send Now',
),
],
],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#F4890A,#F4890A)',
                        'border-color' => 'F4890A',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#DA7B09,#DA7B09)',
                        'border-color' => 'DA7B09',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E21F26,#E21F26)',
                        'border-color' => 'E21F26',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#C81C22,#C81C22)',
                        'border-color' => 'C81C22',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#57B947,#57B947)',
                        'border-color' => '57B947',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#489F46,#489F46)',
                        'border-color' => '489F46',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#007EBF,#007EBF)',
                        'border-color' => '007EBF',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#006DA5,#006DA5)',
                        'border-color' => '006DA5',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '500',
                        'line-height' => '15px',
                        'margin' => '8px 0 0',
                        'padding' => '7px 8px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
],
    'cities' => [
        'kinistino' => [
            'address' => 'P.O. Box 430, Highway #3',
            'city' => 'Kinistino',
            'state' => 'Saskatchewan',
            'country_name' => 'Canada',
            'post_code' => 'S0J 1H0',
            'full_address' => 'P.O. Box 430, Highway #3, Kinistino, Saskatchewan, S0J 1H0',
            'phone' => '1-306-864-3667',
            'lat' => '52.950161',
            'lng' => '-105.032832',
],
        'humboldt' => [
            'address' => 'P.O. Box 3489, Hwy #5 East',
            'city' => 'Humboldt',
            'state' => 'Saskatchewan',
            'country_name' => 'Canada',
            'post_code' => 'S0K 2A0',
            'full_address' => 'P.O. Box 3489, Hwy #5 East, Humboldt, Saskatchewan, S0K 2A0',
            'phone' => '1-306-682-9920',
            'lat' => '52.201910',
            'lng' => '-105.117040',
],
        'prince_albert' => [
            'address' => 'P.O. Box 23128, South Hill Mall, Hwy #2 South',
            'city' => 'Prince Albert',
            'state' => 'Saskatchewan',
            'country_name' => 'Canada',
            'post_code' => 'S6V 8A7',
            'full_address' => 'P.O. Box 23128, South Hill Mall, Hwy #2 South, Prince Albert, Saskatchewan, S6V 8A7',
            'phone' => '1-306-922-2525',
            'lat' => '53.180580',
            'lng' => '-105.754320',
],
],
);