<?php

global $CronConfigs;
$CronConfigs["fedderlychryslerdodgejeep"] = array(
    'name' => 'fedderlychryslerdodgejeep',
    'email' => 'regan@smedia.ca',
    'password' => 'fedderlychryslerdodgejeep',
    'log' => true,
    'max_cost' => 500,
    'cost_distribution' => array(
        'adwords' => 500,
),
    'create' => array(),
    'new_descs' => array(
         array(
            'live' => false,
            'lead_type_' => false,
            'lead_type_new' => false,
            'lead_type_used' => false,
            'lead_type_service' => false,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'inactivity' => true,
            'exit_intent' => true,
            'session_depth' => false,
            'campaign_cap_google' => false,
            'campaign_cap_fb' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 0,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#404450',
            'border_color' => '#E5E5E5',
            'button_color' => array(
                '#FF1010',
                '#FF1010',
),
            'button_color_hover' => array(
                '#002B33',
                '#002B33',
),
            'button_color_active' => array(
                '#002B33',
                '#002B33',
),
            'button_text_color' => '#FFFFFF',
            'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject' => '$200 OFF coupon from Fedderly Chrysler',
            'response_email' => 'Hello [name],<p> Please print this off or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Fedderly Chrysler Team',
            'forward_to' => array(
                'sales@fedderlychrysler.com',
                'mike@fedderlychrysler.com',
                'david@fedderlychrylser.com',
                'marshal@smedia.ca',
),
            'special_to' => array(
                '',
),
            'special_email' => '',
            'display_after' => 30000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'shown_cap_count' => 1,
            'fillup_cap_time_days' => 7,
            'session_close_cap' => 3,
            'inactivity_timeout' => 600000,
            'exit_intent_timeout' => 10000,
            'session_depth_page' => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days' => 7,
            'campaign_fb_cap_count' => 3,
            'campaign_fb_cap_days' => 7,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
                'service_regex' => '',
),
            'custom_div' => '',
            'provider_name' => 'sMedia',
            'source' => 'sMedia smartoffer',
),
         array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model] today',
),
),
    'used_descs' => array(
         array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
),
         array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model] today',
),
),
    'customer_id' => '434-979-3525',
    'banner' => array(
        'template' => 'fedderlychryslerdodgejeep',
        'fb_description' => 'Are you still interested in the [year] [make] [model]? Click for more info!',
        'fb_lookalike_description' => 'Check out this [year] [make] [model]! Click for more information.',
        'styels' => array(
            'new_display' => 'dynamic_banner',
            'used_display' => 'dynamic_banner',
            'new_retargeting' => 'dynamic_banner',
            'used_retargeting' => 'dynamic_banner',
            'new_marketbuyers' => 'dynamic_banner',
            'used_marketbuyers' => 'dynamic_banner',
),
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => '#ffffff',
),
    'lead' => array(
        'live' => true,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
             '#FF1010',
             '#FF1010',
),
        'button_color_hover' => array(
             '#002B33',
             '#002B33',
),
        'button_color_active' => array(
             '#002B33',
             '#002B33',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => '$200 OFF coupon from Fedderly Chrysler',
        'response_email' => 'Hello [name],<p> Please print this off or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Fedderly Chrysler Team',
        'forward_to' => array(
             'sales@fedderlychrysler.com',
             'mike@fedderlychrysler.com',
             'david@fedderlychrylser.com',
             'marshal@smedia.ca',
),
        'respond_from' => 'offers@mail.smedia.ca',
        'forward_from' => 'offers@mail.smedia.ca',
        'thank_you' => '<h1 style="margin: 100px 27px; text-align: center;">Thank you</h1>',
        'lead_in' => array(
            'vdp' => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
            'service_regex' => '',
),
),
    'adf_to' => array(
         'sales@fedderlychrysler.com',
         'mike@fedderlychrysler.com',
         'david@fedderlychylser.com',
         'tania102028@gmail.com',
),
    'form_live' => false,
    'buttons_live' => false,
    'mail_retargeting' => array(
        'enabled' => true,
        'client_id' => '17579',
        'promotion_text' => '',
        'promotion_color' => '#567DC0',
        'overlay_color' => '#FF8500',
        'overlay_text_colour' => '#FFFFFF',
        'price_color' => '#FF8500',
        'coupon_validity' => '7',
),
);