<?php

global $CronConfigs;
$CronConfigs["fishcreeknissancalgaryca"] = array(
    'name' => 'fishcreeknissancalgaryca',
    'email' => 'regan@smedia.ca',
    'password' => 'fishcreeknissancalgaryca',
    'log' => true,
    'combined_feed_mode' => true,
    'lead' => array(
        'live' => true,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'inactivity' => true,
        'exit_intent' => true,
        'session_depth' => false,
        'campaign_cap_google' => false,
        'campaign_cap_fb' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'sent_client_email' => false,
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#C4172C',
            '#C4172C',
),
        'button_color_hover' => array(
            '#000000',
            '#000000',
),
        'button_color_active' => array(
            '#DF3247',
            '#DF3247',
),
        'button_text_color' => '#FFFFFF',
        'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
        'response_email_subject' => 'Claim $200 Off with a purchase from Fish Creek Nissan',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Fish Creek Nissan Team',
        'forward_to' => array(
            '',
),
        'special_to' => array(
            'Array',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'shown_cap_count' => 1,
        'fillup_cap_time_days' => 7,
        'session_close_cap' => 3,
        'inactivity_timeout' => 600000,
        'exit_intent_timeout' => 10000,
        'session_depth_page' => 0,
        'campaign_google_cap_count' => 3,
        'campaign_google_cap_days' => 7,
        'campaign_fb_cap_count' => 3,
        'campaign_fb_cap_days' => 7,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/vehicles\\/[0-9]{4}\\//',
            'service_regex' => '',
),
        'custom_div' => '',
        'provider_name' => 'sMedia',
        'source' => 'sMedia smartoffer',
),
    'form_live' => true,
    'buttons_live' => true,
    'button_algorithm' => 'thompson_sampling|softmax|ucb-1',
    'buttons' => array(
        'payment-options' => array(
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            'locations' => array(
                'default' => null,
),
            'action-target' => '#av_widget-f7ff483b-bd30-45f2-85aa-508d8803de41 div div  a',
            'css-class' => '#av_widget-f7ff483b-bd30-45f2-85aa-508d8803de41 div div  a',
            'css-hover' => '#av_widget-f7ff483b-bd30-45f2-85aa-508d8803de41 div div  a:hover',
            'button_action' => array(
                'form',
                'finance',
),
            'sizes' => array(
                100 => array(),
),
            'texts' => array(
                'payment-options' => array(
                    'target' => '#av_widget-f7ff483b-bd30-45f2-85aa-508d8803de41 div div  a',
                    'values' => array(
                        'Explore Payments',
                        'Calculate Your Payments',
                        'Estimate Payments',
                        'Payment Options',
                        'Financing Options',
),
),
),
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#0E5BFF,#0E5BFF)',
                        'border-color' => '0E5BFF',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#192EFF,#192EFF)',
                        'border-color' => '192EFF',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FFA500,#FFA500)',
                        'border-color' => 'FFA500',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#E49300,#E49300)',
                        'border-color' => 'E49300',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BEBE00,#CDCD00)',
                        'border-color' => 'D2D200',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#D2AB07,#CDA707)',
                        'border-color' => 'DAB108',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#07A73A,#07A73A)',
                        'border-color' => '07A73A',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#069C36,#069734)',
                        'border-color' => '07A238',
                        'color' => '#fff',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '16px',
                        'line-height' => '40px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
),
        'request-a-quote' => array(
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            'locations' => array(
                'default' => null,
),
            'action-target' => '#vdp_button_widget-8 a',
            'css-class' => '#vdp_button_widget-8 a',
            'css-hover' => '#vdp_button_widget-8 a:hover',
            'button_action' => array(
                'form',
                'e-price',
),
            'sizes' => array(
                100 => array(),
),
            'texts' => array(
                'request-a-quote' => array(
                    'target' => '#vdp_button_widget-8 a',
                    'values' => array(
                        'Get a Quote',
                        'Request a Quote',
                        'Get Internet Price',
                        'Get E-Price Now',
                        'Get Special Price',
                        'Get Your Best Price',
                        'Get Your Exclusive Price',
                        'Today\'s Quote',
),
),
),
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#0E5BFF,#0E5BFF)',
                        'border-color' => '0E5BFF',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#192EFF,#192EFF)',
                        'border-color' => '192EFF',
                        'color' => '#fff',
),
),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FFA500,#FFA500)',
                        'border-color' => 'FFA500',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#E49300,#E49300)',
                        'border-color' => 'E49300',
                        'color' => '#fff',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BEBE00,#CDCD00)',
                        'border-color' => 'D2D200',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#D2AB07,#CDA707)',
                        'border-color' => 'DAB108',
                        'color' => '#fff',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#07A73A,#07A73A)',
                        'border-color' => '07A73A',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#069C36,#069734)',
                        'border-color' => '07A238',
                        'color' => '#fff',
),
),
),
),
        'test-drive' => array(
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            'locations' => array(
                'default' => null,
),
            'action-target' => '#vdp_button_widget-10  a',
            'css-class' => '#vdp_button_widget-10 a',
            'css-hover' => '#vdp_button_widget-10 a:hover',
            'button_action' => array(
                'form',
                'test-drive',
),
            'sizes' => array(
                100 => array(),
),
            'texts' => array(
                'test-drive' => array(
                    'target' => '#vdp_button_widget-10 a',
                    'values' => array(
                        'Schedule a Test Drive',
                        'Request a Test Drive',
                        'Schedule Your Visit',
                        'Test Drive Today',
                        'Want To Test Drive?',
),
),
),
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#0E5BFF,#0E5BFF)',
                        'border-color' => '0E5BFF',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#192EFF,#192EFF)',
                        'border-color' => '192EFF',
                        'color' => '#fff',
),
),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FFA500,#FFA500)',
                        'border-color' => 'FFA500',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#E49300,#E49300)',
                        'border-color' => 'E49300',
                        'color' => '#fff',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BEBE00,#CDCD00)',
                        'border-color' => 'D2D200',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#D2AB07,#CDA707)',
                        'border-color' => 'DAB108',
                        'color' => '#fff',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#07A73A,#07A73A)',
                        'border-color' => '07A73A',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#069C36,#069734)',
                        'border-color' => '07A238',
                        'color' => '#fff',
),
),
),
),
        'financing' => array(
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            'locations' => array(
                'default' => null,
),
            'action-target' => 'div a[data-av-button-product="credit"]',
            'css-class' => 'div a[data-av-button-product="credit"]',
            'css-hover' => 'div a[data-av-button-product="credit"]:hover',
            'button_action' => array(
                'form',
                'finance',
),
            'sizes' => array(
                100 => array(),
),
            'texts' => array(
                'financing' => array(
                    'target' => 'div a[data-av-button-product="credit"]',
                    'values' => array(
                        'Get Financed Today!',
                        'Apply For Financing',
                        'Financing Available',
                        'Special Finance Offers',
                        'Get Approved Today',
                        'Get Your Loan Online',
),
),
),
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#0E5BFF,#0E5BFF)',
                        'border-color' => '0E5BFF',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#192EFF,#192EFF)',
                        'border-color' => '192EFF',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FFA500,#FFA500)',
                        'border-color' => 'FFA500',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#E49300,#E49300)',
                        'border-color' => 'E49300',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BEBE00,#CDCD00)',
                        'border-color' => 'D2D200',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#D2AB07,#CDA707)',
                        'border-color' => 'DAB108',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#07A73A,#07A73A)',
                        'border-color' => '07A73A',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#069C36,#069734)',
                        'border-color' => '07A238',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
),
        'trade-in' => array(
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            'locations' => array(
                'default' => null,
),
            'action-target' => 'div a[data-av-button-product="tradein"]',
            'css-class' => 'div a[data-av-button-product="tradein"]',
            'css-hover' => 'div a[data-av-button-product="tradein"]:hover',
            'button_action' => array(
                'form',
                'trade-in',
),
            'sizes' => array(
                100 => array(),
),
            'texts' => array(
                'trade-in' => array(
                    'target' => 'div a[data-av-button-product="tradein"]',
                    'values' => array(
                        'Value Your Trade',
                        'Trade-In Offer',
                        'We Want Your Trade!',
                        'Trade-In Appraisal',
                        'Appraise Your Trade',
),
),
),
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#0E5BFF,#0E5BFF)',
                        'border-color' => '0E5BFF',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#192EFF,#192EFF)',
                        'border-color' => '192EFF',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FFA500,#FFA500)',
                        'border-color' => 'FFA500',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#E49300,#E49300)',
                        'border-color' => 'E49300',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BEBE00,#CDCD00)',
                        'border-color' => 'D2D200',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#D2AB07,#CDA707)',
                        'border-color' => 'DAB108',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#07A73A,#07A73A)',
                        'border-color' => '07A73A',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#069C36,#069734)',
                        'border-color' => '07A238',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '16px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0px',
                        'padding' => '12px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
),
),
);