<?php

global $CronConfigs;
$CronConfigs["fortfrancesgm"] = array(
    'name' => 'fortfrancesgm',
    'email' => 'regan@smedia.ca',
    'password' => 'fortfrancesgm',
    'log' => true,
    'combined_feed_mode' => true,
    'fb_brand' => '[year] [make] [model] - [body_style]',
    'fb_title' => '[year] [make] [model] [price]',
    'bing_account_id' => 156002977,
    'max_cost' => 250,
    'cost_distribution' => array(
        'adwords' => 150,
        'youtube' => 100,
),
    'create' => array(),
    'new_descs' => array(
        array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
),
        array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model] today',
),
),
    'used_descs' => array(
        array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
),
        array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model] today',
),
),
    'customer_id' => '298-616-7164',
    'banner' => array(
        'template' => 'fortfrancesgm',
        'fb_description' => 'Are you still interested in the [year] [make] [model]? Click for more info!',
        'fb_lookalike_description' => 'Check out this [year] [make] [model] today! Click for more information.',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => '#ffffff',
        'styels' => array(
            'new_display' => 'dynamic_banner',
            'used_display' => 'dynamic_banner',
            'new_retargeting' => 'dynamic_banner',
            'used_retargeting' => 'dynamic_banner',
            'new_marketbuyers' => 'dynamic_banner',
            'used_marketbuyers' => 'dynamic_banner',
),
),
    'lead' => array(
        'live' => false,
        'lead_type_' => false,
        'lead_type_new' => false,
        'lead_type_used' => false,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'inactivity' => true,
        'exit_intent' => true,
        'session_depth' => false,
        'campaign_cap_google' => false,
        'campaign_cap_fb' => false,
        'device_type' => array(
            'mobile' => false,
            'desktop' => false,
            'tablet' => false,
),
        'sent_client_email' => true,
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#162652',
            '#162652',
),
        'button_color_hover' => array(
            '#525C77',
            '#525C77',
),
        'button_color_active' => array(
            '#525C77',
            '#525C77',
),
        'button_text_color' => '#FFFFFF',
        'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
        'response_email_subject' => 'Book virtual test drive',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Fort France GM Team',
        'forward_to' => array(
            'ron@fortfrancesgm.com',
            'chris@fortfrancesgm.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'shown_cap_count' => 1,
        'fillup_cap_time_days' => 7,
        'session_close_cap' => 3,
        'inactivity_timeout' => 600000,
        'exit_intent_timeout' => 10000,
        'session_depth_page' => 0,
        'campaign_google_cap_count' => 3,
        'campaign_google_cap_days' => 7,
        'campaign_fb_cap_count' => 3,
        'campaign_fb_cap_days' => 7,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/en\\/inventory\\/(?:new|used)/',
            'service_regex' => '',
),
        'custom_div' => '',
        'provider_name' => 'sMedia',
        'source' => 'sMedia smartoffer',
),
    'smart_memo' => array(
        'live' => false,
        'live_new' => false,
        'live_used' => false,
        'live_home' => false,
        'live_service' => false,
        'video' => false,
        'hide_redirection' => false,
        'video_url' => 'https://www.youtube.com/watch?v=wCFi9s3LhBU&ab_channel=sMediaProofs',
        'button_text' => 'BUILD AND PRICE',
        'url' => 'https://www.fortfrancesgm.com/en/shop-online',
        'home_url' => 'https://www.fortfrancesgm.com/en',
        'service_regex' => '',
        'bg_color' => '#ADADAD',
        'text_color' => '#404450',
        'border_color' => '#969696',
        'button_text_color' => '#DEDEDE',
        'button_color' => array(
            '#FF0000',
            '#FF0000',
),
        'button_color_hover' => array(
            '#D92929',
            '#D92929',
),
        'button_color_active' => array(
            '#D92929',
            '#D92929',
),
),
);