<?php

global $CronConfigs;
$CronConfigs["frankdunntoyota"] = array(
    'name'               => 'frankdunntoyota',
    'email'              => 'regan@smedia.ca',
    'password'           => 'frankdunntoyota',
    'fb_brand'           => '[year] [make] [model] - [body_style]',
    'log'                => true,
    'combined_feed_mode' => true,
    'max_cost'           => 400,
    'cost_distribution'  => array(
        'adwords' => 400,
    ),
    'customer_id'        => '497-434-0656',
    'create'             => array(),
    'new_descs'          => array(
        array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
        ),
        array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model] today',
        ),
    ),
    'used_descs'         => array(
        array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
        ),
        array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model] today',
        ),
    ),
    'banner'             => array(
        'template'                   => 'frankdunntoyota',
        'fb_description'             => 'Finance the [year] [make] [Model] [trim] from [finance] bi-weekly at [finance_rate] APR for [finance_term] months. All-in cash price [price]. *See dealer for details.',
        'fb_agedstock_description'   => 'Finance the [year] [make] [Model] [trim] *In Store Special!!! From [finance] bi-weekly at [finance_rate] APR for [finance_term] months. All-in cash price [price]. *See dealer for details.',
        'fb_dynamiclead_description' => 'Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to answer any questions.',
        'flash_style'                => 'default',
        'styels'                     => array(
            'new_display'       => 'dynamic_banner',
            'used_display'      => 'dynamic_banner',
            'new_retargeting'   => 'dynamic_banner',
            'used_retargeting'  => 'dynamic_banner',
            'new_marketbuyers'  => 'dynamic_banner',
            'used_marketbuyers' => 'dynamic_banner',
        ),
        'border_color'               => '#282828',
        'font_color'                 => '#ffffff',
        'fb_marketplace_description' => '[description]',
    ),
    'lead'               => array(
        'used' => array(
            'live'                      => false,
            'lead_type_'                => false,
            'lead_type_new'             => false,
            'lead_type_used'            => false,
            'lead_type_service'         => false,
            'shown_cap'                 => false,
            'fillup_cap'                => false,
            'session_close'             => false,
            'inactivity'                => false,
            'exit_intent'               => false,
            'session_depth'             => false,
            'campaign_cap_google'       => false,
            'campaign_cap_fb'           => false,
            'device_type'               => array(
                'mobile'  => true,
                'desktop' => true,
                'tablet'  => true,
            ),
            'sent_client_email'         => true,
            'offer_minimum_price'       => 0,
            'offer_maximum_price'       => 10000000,
            'bg_color'                  => '#EFEFEF',
            'text_color'                => '#404450',
            'border_color'              => '#E5E5E5',
            'button_color'              => array(
                '#EB0A1E',
                '#EB0A1E',
            ),
            'button_color_hover'        => array(
                '#000000',
                '#000000',
            ),
            'button_color_active'       => array(
                '#000000',
                '#000000',
            ),
            'button_text_color'         => '#FFFFFF',
            'forward_email_subject'     => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject'    => 'Get $200 off coupon from Frank Dunn Toyota',
            'response_email'            => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Frank Dunn Toyota Team',
            'forward_to'                => array(
                'marshal@smedia.ca',
                'leads@toyotapa.ca',
            ),
            'special_to'                => array(
                'smedia@frankdunntoyota.net',
            ),
            'special_email'             => '',
            'display_after'             => 30000,
            'retarget_after'            => 5000,
            'fb_retarget_after'         => 5000,
            'adword_retarget_after'     => 5000,
            'visit_count'               => 0,
            'shown_cap_count'           => 1,
            'fillup_cap_time_days'      => 7,
            'session_close_cap'         => 3,
            'inactivity_timeout'        => 600000,
            'exit_intent_timeout'       => 10000,
            'session_depth_page'        => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days'  => 7,
            'campaign_fb_cap_count'     => 3,
            'campaign_fb_cap_days'      => 7,
            'video_smart_offer'         => false,
            'video_smart_offer_form'    => false,
            'video_url'                 => '',
            'video_title'               => '',
            'video_description'         => '',
            'lead_in'                   => array(
                'vdp'           => '/\\/inventory\\/(?:new|used|certified-used)-[0-9]{4}-/',
                'service_regex' => '',
            ),
            'custom_div'                => '',
            'provider_name'             => 'sMedia',
            'source'                    => 'sMedia smartoffer',
        ),
        'new'  => array(
            'live'                      => false,
            'lead_type_'                => false,
            'lead_type_new'             => false,
            'lead_type_used'            => false,
            'lead_type_service'         => false,
            'shown_cap'                 => false,
            'fillup_cap'                => false,
            'session_close'             => false,
            'inactivity'                => false,
            'exit_intent'               => false,
            'session_depth'             => false,
            'campaign_cap_google'       => false,
            'campaign_cap_fb'           => false,
            'device_type'               => array(
                'mobile'  => true,
                'desktop' => true,
                'tablet'  => true,
            ),
            'sent_client_email'         => true,
            'offer_minimum_price'       => 0,
            'offer_maximum_price'       => 10000000,
            'bg_color'                  => '#EFEFEF',
            'text_color'                => '#404450',
            'border_color'              => '#E5E5E5',
            'button_color'              => array(
                '#EB0A1E',
                '#EB0A1E',
            ),
            'button_color_hover'        => array(
                '#000000',
                '#000000',
            ),
            'button_color_active'       => array(
                '#000000',
                '#000000',
            ),
            'button_text_color'         => '#FFFFFF',
            'forward_email_subject'     => '#[monthly_count] Smedia Coupon Lead.',
            'response_email_subject'    => 'Get $200 off voucher from Prince Albert Toyota',
            'response_email'            => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Prince Albert Toyota Team',
            'forward_to'                => array(
                'marshal@smedia.ca',
                'leads@toyotapa.ca',
            ),
            'special_to'                => array(
                'smedia@frankdunntoyota.net',
            ),
            'special_email'             => '',
            'display_after'             => 30000,
            'retarget_after'            => 5000,
            'fb_retarget_after'         => 5000,
            'adword_retarget_after'     => 5000,
            'visit_count'               => 0,
            'shown_cap_count'           => 1,
            'fillup_cap_time_days'      => 7,
            'session_close_cap'         => 3,
            'inactivity_timeout'        => 600000,
            'exit_intent_timeout'       => 10000,
            'session_depth_page'        => 0,
            'campaign_google_cap_count' => 3,
            'campaign_google_cap_days'  => 7,
            'campaign_fb_cap_count'     => 3,
            'campaign_fb_cap_days'      => 7,
            'video_smart_offer'         => false,
            'video_smart_offer_form'    => false,
            'video_url'                 => '',
            'video_title'               => '',
            'video_description'         => '',
            'lead_in'                   => array(
                'vdp'           => '/\\/inventory\\/(?:new|used|certified-used)-[0-9]{4}-/',
                'service_regex' => '',
            ),
            'custom_div'                => '',
            'provider_name'             => 'sMedia',
            'source'                    => 'sMedia smartoffer',
        ),
    ),
    'adf_to'             => array(
        'smedia@frankdunntoyota.net',
    ),
    'form_live'          => false,
    'button_algorithm'   => 'thompson_sampling|softmax|ucb-1',
    'buttons_live'       => false,
);