<?php

global $CronConfigs;
$CronConfigs["harrisoceansidegmcom"] = array(
    "name" => " harrisoceansidegmcom",
    "email" => "regan@smedia.ca",
    "password" => " harrisoceansidegmcom",
    "log" => true,
    'max_cost' => 300,
    'cost_distribution' => array(
        'adwords' => 300,
    ),
    'customer_id' => '549-232-4496',
    'combined_feed_mode' => true,
    "banner" => array(
        "template" => "harrisoceansidegmcom",
        //"fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
        'fb_description_new' => "Finance the [year] [make] [model]  for [finance] bi-weekly for [finance_term] months. Our cash price [price]. *See dealer for details.",
        'fb_description_used' => "Are you still interested in this [year] [make] [model] ? Drive it home for [price]. Shop now!",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today! Click for more information.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
    ),
    "lead" => array(
        'live' => true,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
        ),
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#1E4387',
            '#1E4387',
        ),
        'button_color_hover' => array(
            '#1A3972',
            '#1A3972',
        ),
        'button_color_active' => array(
            '#1A3972',
            '#1A3972',
        ),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => 'Request At-Home Test Drive',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Harris Oceanside GM Team',
        'forward_to' => array(
            'harrisoceansidecustomercare@harrisauto.ca',
            'marshal@smedia.ca',
        ),
        'special_to' => array(
            '',
        ),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/inventory\\/(?:new|used)-[0-9]{4}-/',
            'service' => '',
        ),
    ),
);
