<?php

global $CronConfigs;
$CronConfigs["heartlandhonda"] = array(
    'password' => 'heartlandhonda',
    'email' => 'regan@smedia.ca',
    'fb_brand' => '[year] [make] [model] [trim] - [body_style]',
    'log' => true,
    'customer_id' => '302-970-7629',
    'max_cost' => 9306,
    'cost_distribution' => array(
        'adwords' => 9306,
),
    'custom' => 0.0,
    'lead' => array(
        'new' => array(
            'live' => true,
            'lead_type_' => true,
            'lead_type_new' => true,
            'lead_type_used' => false,
            'lead_type_service' => false,
            'shown_cap' => false,
            'fillup_cap' => false,
            'session_close' => false,
            'device_type' => array(
                'mobile' => true,
                'desktop' => true,
                'tablet' => true,
),
            'sent_client_email' => true,
            'offer_minimum_price' => 15000,
            'offer_maximum_price' => 10000000,
            'bg_color' => '#EFEFEF',
            'text_color' => '#404450',
            'border_color' => '#E5E5E5',
            'button_color' => array(
                0 => '#D32121',
                1 => '#D32121',
),
            'button_color_hover' => array(
                0 => '#000000',
                1 => '#000000',
),
            'button_color_active' => array(
                0 => '#000000',
                1 => '#000000',
),
            'button_text_color' => '#FFFFFF',
            'response_email_subject' => '$250 trade in coupon from Heartland Honda',
            'response_email' => 'Hello [name],<p> Thank you for signing up for our offer!  Please print this off or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Heartland Honda Team',
            'forward_to' => array(
                0 => 'info@heartlandhonda.com',
                1 => 'marshal@smedia.ca',
),
            'special_to' => array(
                0 => '',
),
            'special_email' => '',
            'display_after' => 45000,
            'retarget_after' => 5000,
            'fb_retarget_after' => 5000,
            'adword_retarget_after' => 5000,
            'visit_count' => 0,
            'video_smart_offer' => false,
            'video_smart_offer_form' => false,
            'video_url' => '',
            'video_title' => '',
            'video_description' => '',
            'lead_in' => array(
                'vdp' => '/\\/(?:New|Pre-owned)-Inventory-[0-9]{4}-/i',
                'service_regex' => '',
),
),
),
    'create' => array(),
    'new_descs' => array(
        0 => array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model]',
),
        1 => array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
),
),
    'used_descs' => array(
        0 => array(
            'desc1' => 'Call us today about the ',
            'desc2' => '[year] [make] [model]',
),
        1 => array(
            'desc1' => 'Test Drive the [year]',
            'desc2' => '[make] [model] today.',
),
),
    'banner' => array(
        'template' => 'heartlandhonda',
        'fb_banner_title' => '[year] [make] [model] [trim] - [price]',
        'fb_aia_description' => '[description]. Check out this [year] [make] [model] today! Click the \'Dealership Website\' link below for more information.',
        'fb_description' => 'Are you still interested in the [year] [make] [model] [trim]? Want to test ride it today? Click for more info.',
        'fb_lookalike_description' => 'Come see us today! Want to test ride the [year] [make] [model] [trim]? Click for more info.',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'styels' => array(
            'new_display' => 'dynamic_banner',
            'used_display' => 'dynamic_banner',
            'new_retargeting' => 'dynamic_banner',
            'used_retargeting' => 'dynamic_banner',
            'new_marketbuyers' => 'dynamic_banner',
            'used_marketbuyers' => 'dynamic_banner',
),
        'fb_style' => 'facebook_new_ad',
        'font_color' => '#ffffff',
),
    'mail_retargeting' => array(
        'enabled' => true,
        'client_id' => '17584',
        'promotion_text' => '',
        'promotion_color' => '#567DC0',
        'overlay_color' => '#FF8500',
        'overlay_text_colour' => '#FFFFFF',
        'price_color' => '#FF8500',
        'coupon_validity' => '7',
),
    'name' => 'heartlandhonda',
);