<?php

global $CronConfigs;
$CronConfigs["hmpexeter"] = array(
    "name" => " hmpexeter",
    "email" => "regan@smedia.ca",
    "password" => " hmpexeter",
    "log" => true,
    "fb_title" => "[year] [make] [model] [price]",
    'fb_brand' => '[year] [make] [model] - [body_style]',
    "banner" => array(
        "template" => "hmpexeter",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more information.",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today! Click for more information.",
        //"fb_dynamiclead_description"	=> "Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to answer any questions.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "ffffff",
),
    "lead" => array(
        'live' => true,
        'lead_type_' => true,
        'lead_type_new' => false,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'offer_minimum_price' => 10000,
        'offer_maximum_price' => 100000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#3899CB',
            '#3899CB',
),
        'button_color_hover' => array(
            '#205B79',
            '#205B79',
),
        'button_color_active' => array(
            '#205B79',
            '#205B79',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => 'June Offers at Huron Motor Products. We\'re here to help!',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Huron Motor Products',
        'forward_to' => array(
            'sales@hmpexeter.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/(?:new|used)\\/vehicle\\/[0-9]{4}-/i',
            'service' => '',
),
),
);