<?php

global $CronConfigs;
$CronConfigs["kiasudburycom"] = array(
    'name' => 'kiasudburycom',
    'email' => 'regan@smedia.ca',
    'password' => 'kiasudburycom',
    'log' => true,
    'combined_feed_mode' => true,
    'fb_title' => "[year] [make] [model] [trim] [price]",
    'banner' => array(
        'template' => 'kiasudburycom',
        "fb_banner_title" => '[year] [make] [model] [trim]',
        'fb_description' => 'Are you still interested in the [year] [make] [model] [trim]? Click for more info!',
        'fb_lookalike_description' => 'Check out this [year] [make] [model] [trim] today! Click for more information.',
        'flash_style' => 'default',
        'border_color' => '#282828',
        'font_color' => '#ffffff',
),
    'lead' => array(
        'live' => false,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'inactivity' => true,
        'exit_intent' => true,
        'session_depth' => false,
        'campaign_cap_google' => false,
        'campaign_cap_fb' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'sent_client_email' => true,
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#05141F',
            '#05141F',
),
        'button_color_hover' => array(
            '#21232E',
            '#21232E',
),
        'button_color_active' => array(
            '#05141F',
            '#05141F',
),
        'button_text_color' => '#FFFFFF',
        'forward_email_subject' => '#[monthly_count] Smedia Coupon Lead.',
        'response_email_subject' => 'We Will Buy Your Car',
        'response_email' => 'Hello [name],<p> Thank you for filling out the form. Our product specialist will contact you soon.</p><br><img src=\\"[image]\\"/><p><br><br>Kia Sudbury Team',
        'forward_to' => array(
            '',
),
        'special_to' => array(
            'leads-kia-sudbury-motors@emailtolead.com',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'shown_cap_count' => 1,
        'fillup_cap_time_days' => 7,
        'session_close_cap' => 3,
        'inactivity_timeout' => 600000,
        'exit_intent_timeout' => 10000,
        'session_depth_page' => 0,
        'campaign_google_cap_count' => 3,
        'campaign_google_cap_days' => 7,
        'campaign_fb_cap_count' => 3,
        'campaign_fb_cap_days' => 7,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/www\\.kiasudbury\\.com\\/[0-9]{4}-/i',
            'service_regex' => '',
),
        'custom_div' => '',
        'provider_name' => 'sMedia',
        'source' => 'sMedia smartoffer',
        'button_text' => 'submit',
),
);