<?php

global $CronConfigs;
$CronConfigs["motounitedlahabracom"] = array(
    "name" => " motounitedlahabracom",
    "email" => "regan@smedia.ca",
    "password" => " motounitedlahabracom",
    "log" => true,
    'combined_feed_mode' => true,
    "banner" => array(
        "template" => "motounitedlahabracom",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more information.",
        "fb_lookalike_description" => "Check out this [year] [make] [model]! Click for more information.",
        //"fb_dynamiclead_description"	=> "Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to answer any questions.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "ffffff",
),
    "lead" => array(
        'live' => true,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#E31B23',
            '#E31B23',
),
        'button_color_hover' => array(
            '#650B0F',
            '#650B0F',
),
        'button_color_active' => array(
            '#650B0F',
            '#650B0F',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => '$200 off coupon from Moto United -  Lahabra',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Moto United -  Lahabra Team',
        'forward_to' => array(
            'cameron@motounited.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/default\\.asp/i',
            'service' => '',
),
),
    'form_live' => false,
    'buttons_live' => false,
    'buttons' => [
        'request-a-quote' => [
            'url-match' => '/\\/default.asp\\?page=(?:x|xNew|xPreOwned)InventoryDetail/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'li.textbutton.invGetQuote a',
            'css-class' => 'li.textbutton.invGetQuote a',
            'css-hover' => 'li.textbutton.invGetQuote a:hover',
            //            'button_action' => [
            //                'form',
            //                'e-price',
            //            ],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'li.textbutton.invGetQuote a',
                    'values' => array(
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Get Price Updates',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Local Pricing',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Best Price',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Get Current Market Price',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Get Internet Price Now',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Request A Quote',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Inquire Now!',
                        '<span class="textbuttonIcon fa fa-comment-o"></span>Get Your Exclusive Price',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E51B24,#E51B24)',
                        'border-color' => 'FF4D71',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#8B0F15,#8B0F15)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#3A7FEA,#3A7FEA)',
                        'border-color' => '00B4FF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#234F92,#234F92)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FDAC2E,#FDAC2E)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#AA6801,#AA6801)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'gray' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#737373,#737373)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#343333,#343333)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
),
],
        'trade-in' => [
            'url-match' => '/\\/default.asp\\?page=(?:x|xNew|xPreOwned)InventoryDetail/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'li.textbutton.invValueTrade a',
            'css-class' => 'li.textbutton.invValueTrade a',
            'css-hover' => 'li.textbutton.invValueTrade a:hover',
            //            'button_action' => [
            //                'form',
            //                'trade-in',
            //            ],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'trade-in' => [
                    'target' => 'li.textbutton.invValueTrade a',
                    'values' => array(
                        '<span class="textbuttonIcon fa fa-exchange"></span>Value Your Trade',
                        '<span class="textbuttonIcon fa fa-exchange"></span>Trade In Your Ride',
                        '<span class="textbuttonIcon fa fa-exchange"></span>We\'ll Buy Your Car',
                        '<span class="textbuttonIcon fa fa-exchange"></span>Trade Offer',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E51B24,#E51B24)',
                        'border-color' => 'FF4D71',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#8B0F15,#8B0F15)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#3A7FEA,#3A7FEA)',
                        'border-color' => '00B4FF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#234F92,#234F92)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FDAC2E,#FDAC2E)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#AA6801,#AA6801)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'gray' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#737373,#737373)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#343333,#343333)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
),
],
        'test-drive' => [
            'url-match' => '/\\/default.asp\\?page=(?:x|xNew|xPreOwned)InventoryDetail/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'li.textbutton.invScheduleRide a',
            'css-class' => 'li.textbutton.invScheduleRide a',
            'css-hover' => 'li.textbutton.invScheduleRide a:hover',
            //            'button_action' => [
            //                'form',
            //                'test-drive',
            //            ],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'test-drive' => [
                    'target' => 'li.textbutton.invScheduleRide a',
                    'values' => array(
                        '<span class="textbuttonIcon fa fa-envelope-o"></span>Book Test Drive',
                        '<span class="textbuttonIcon fa fa-envelope-o"></span>Test Drive Now',
                        '<span class="textbuttonIcon fa fa-envelope-o"></span>Schedule Your Test Drive',
                        '<span class="textbuttonIcon fa fa-envelope-o"></span>Request A Test Drive',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E51B24,#E51B24)',
                        'border-color' => 'FF4D71',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#8B0F15,#8B0F15)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#3A7FEA,#3A7FEA)',
                        'border-color' => '00B4FF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#234F92,#234F92)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FDAC2E,#FDAC2E)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#AA6801,#AA6801)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'gray' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#737373,#737373)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#343333,#343333)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
),
],
        'financing' => [
            'url-match' => '/\\/default.asp\\?page=(?:x|xNew|xPreOwned)InventoryDetail/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'li.textbutton.invGetFinancing a',
            'css-class' => 'li.textbutton.invGetFinancing a',
            'css-hover' => 'li.textbutton.invGetFinancing a:hover',
            //            'button_action' => [
            //                'form',
            //                'finance',
            //            ],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'financing' => [
                    'target' => 'li.textbutton.invGetFinancing a',
                    'values' => array(
                        '<span class="textbuttonIcon fa fa-dollar"></span>Financing Options',
                        '<span class="textbuttonIcon fa fa-dollar"></span>Calculate Your Payments',
                        '<span class="textbuttonIcon fa fa-dollar"></span>Estimate Payments',
                        '<span class="textbuttonIcon fa fa-dollar"></span>Estimate Payments',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#E51B24,#E51B24)',
                        'border-color' => 'FF4D71',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#8B0F15,#8B0F15)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#3A7FEA,#3A7FEA)',
                        'border-color' => '00B4FF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#234F92,#234F92)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#FDAC2E,#FDAC2E)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#AA6801,#AA6801)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
                'gray' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#737373,#737373)',
                        'border-color' => 'FF4B00',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#343333,#343333)',
                        'border-color' => '000000',
                        'color' => '#FFFFFF',
                        'display' => 'block',
                        'padding' => '14px 15px',
                        'position' => 'relative',
                        'font-size' => '15px',
                        'line-height' => '1.42857143',
                        'text-transform' => 'uppercase',
),
),
),
],
],
);