<?php

global $CronConfigs;
$CronConfigs["murraychev"] = array(
    "name" => "murraychev",
    "email" => "regan@smedia.ca",
    "password" => "murraychev",
    "log" => true,
    "fb_title" => "[year] [make] [model] [price]",
    "banner" => array(
        "template" => "murraychev",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
        "fb_lookalike_description" => "Check out this [year] [make] [model]! Click for more information.",
        "fb_dynamiclead_description" => "Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to answer any questions.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "ffffff",
    ),
    'adf_to' => array(
        'murray.chev.medicine.hat.leads@gmail.com',
    ),
    'form_live' => false,
    'buttons_live' => false,
    'buttons' => [
        'request-a-quote' => [
            'url-match' => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => 'a[data-href *=eprice]',
            'css-class' => 'a[data-href *=eprice]',
            'css-hover' => 'a[data-href *=eprice]:hover',
            'button_action' => [
                'form',
                'e-price',
            ],
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'a[data-href *=eprice]',
                    'values' => array(
                        'Get Price Updates',
                        'Get Current Market Price',
                        'Get Internet Price Now',
                        'Get A Quote',
                        'Inquire Now!',
                        'Confirm Availability',
                        'Get Your Exclusive Price',
                    ),
                ],
            ],
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#009DE1,#009DE1)',
                        'border-color' => '#D27606',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#008BC7,#008BC7)',
                        'border-color' => '#AB5E00',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'gray' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#B2B2B2,#B2B2B2)',
                        'border-color' => '#D27606',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#989898,#989898)',
                        'border-color' => '#AB5E00',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#F0BA02,#F0BA02)',
                        'border-color' => '#D27606',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D6A602,#D6A602)',
                        'border-color' => '#AB5E00',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
        'test-drive' => [
            'url-match' => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
            ],
            'action-target' => '.request_a_testdrive',
            'css-class' => '.request_a_testdrive',
            'css-hover' => '.request_a_testdrive:hover',
            'button_action' => [
                'form',
                'test-drive',
            ],
            'sizes' => [
                '100' => [],
            ],
            'texts' => [
                'test-drive' => [
                    'target' => '.request_a_testdrive',
                    'values' => array(
                        'Book Test Drive',
                        'Test Drive Now',
                        'Schedule a Test Drive',
                        'Schedule Your Test Drive',
                        'Request A Test Drive',
                    ),
                ],
            ],
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#009DE1,#009DE1)',
                        'border-color' => '#D27606',
                        'color' => '#fff',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 11px',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#008BC7,#008BC7)',
                        'border-color' => '#AB5E00',
                        'color' => '#fff',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 11px',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'gray' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#B2B2B2,#B2B2B2)',
                        'border-color' => '#D27606',
                        'color' => '#fff',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 11px',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#989898,#989898)',
                        'border-color' => '#AB5E00',
                        'color' => '#fff',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 11px',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
                'yellow' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#F0BA02,#F0BA02)',
                        'border-color' => '#D27606',
                        'color' => '#fff',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 11px',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                    'hover' => array(
                        'background' => 'linear-gradient(#D6A602,#D6A602)',
                        'border-color' => '#AB5E00',
                        'color' => '#fff',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 11px',
                        'padding' => '20px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                    ),
                ),
            ),
        ],
    ],
);