<?php

global $CronConfigs;
$CronConfigs["pinetreeford"] = array(
    'password' => 'pinetreeford',
    'fb_brand' => '[year] [make] [model] - [body_style]',
    "email" => "regan@smedia.ca",
    'log' => true,
    "customer_id" => "334-158-7923",
    'max_cost' => 2400,
    'cost_distribution' => array(
        'adwords' => 2400,
),
    "create" => array(
        "new_search" => yes,
        "used_search" => yes,
),
    "new_descs" => array(
        array(
            "desc1" => "Test Drive the [year]",
            "desc2" => "[make] [model] today.",
),
        array(
            "desc1" => "Call us today about the ",
            "desc2" => "[year] [make] [model]",
),
),
    "used_descs" => array(
        array(
            "desc1" => "Test Drive the [year]",
            "desc2" => "[make] [model] today.",
),
        array(
            "desc1" => "Call us today about the ",
            "desc2" => "[year] [make] [model]",
),
),
    "banner" => array(
        "template" => "pinetreeford",
        "fb_retargeting_description" => "Are you still interested in the [year] [make] [model] [trim]? Click for more info,",
        "fb_retargeting_description_new" => "Are you still interested in the [year] [make] [model] [trim]?  Sale price is [price] + sales taxes. Stock #: [stock_number]",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today. Click for more information.",
        "fb_dynamiclead_description" => "Still interested in the [year] [make] [model]? Click below, fill in your info to get \$200 OFF, and a product specialist will be in touch to aid in any questions.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
        "styels" => array(
            "new_display" => "custom_banner",
            "used_display" => "custom_banner",
            "new_retargeting" => "custom_banner",
            "used_retargeting" => "custom_banner",
            "new_marketbuyers" => "custom_banner",
            "used_marketbuyers" => "custom_banner",
),
),
    "lead" => array(
        'live' => false,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#1F4581',
            '#1F4581',
),
        'button_color_hover' => array(
            '#3968A5',
            '#3968A5',
),
        'button_color_active' => array(
            '#333333',
            '#333333',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => '$200 OFF from Pine Tree Ford',
        'response_email' => 'Hello [name],<p> Please print this off or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Pine Tree Ford Team',
        'forward_to' => array(
            'marshal@smedia.ca',
            'emil@smedia.ca',
),
        'special_to' => array(
            'pinetreeford_fdc@edrive-valet.com
smedia@pinetree-ford.net',
),
        'special_email' => '<?xml version="1.0"?>
			<?adf version="1.0"?>
			<adf>
				<prospect>
					<id sequence="[total_count]" source="Pine Tree Ford"></id>
					<requestdate>[fdt]</requestdate>
					<vehicle interest="buy" status="[stock_type]">
						<year>[year]</year>
						<make>[make]</make>
						<model>[model]</model>
						<stock>[stock_number]</stock>
					</vehicle>
					<customer>
						<contact>
							<name part="full">[name]</name>
							<email>[email]</email>
							<phone>[phone]</phone>
						</contact>
					</customer>
					<vendor>
						<contact>
							<name part="full">Pine Tree Ford</name>
							<email>[dealer_email]</email>
						</contact>
					</vendor>
					<provider>
						<name part="full">sMedia</name>
						<url>http://smedia.ca</url>
						<email>offers@mail.smedia.ca</email>
						<phone>855-775-0062</phone>
					</provider>
				</prospect>
			</adf>',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
            'service' => '',
),
),
    'adf_to' => [
        'pinetreeford_fdc@edrive-valet.com',
],
    'form_live' => true,
    'button_algorithm' => 'thompson_sampling|softmax|ucb-1|default',
    'buttons_live' => true,
    'buttons' => [
        'request-information' => [
            'url-match' => '/\\/(?:new|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[href*="lead-form"]',
            'css-class' => 'a[href*="lead-form"]',
            'css-hover' => 'a[href*="lead-form"]:hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-information' => [
                    'target' => 'a[href*="lead-form"]',
                    'values' => array(
                        'Get More Info',
                        'More Information',
                        'Learn More',
                        'Ask A Question',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'Used finance' => [
            'url-match' => '/\\/(?:new|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[href*=financing].ui-button',
            'css-class' => 'a[href*=financing].ui-button',
            'css-hover' => 'a[href*=financing].ui-button:hover',
            'button_action' => [
                'form',
                'finance',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-information' => [
                    'target' => 'a[href*=financing].ui-button',
                    'values' => array(
                        'Apply for Financing',
                        'No hassle financing',
                        'Financing Available',
                        'Get Financed Today',
                        'Explore Payments',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'request-a-quote' => [
            'url-match' => '/\\/(?:new|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[href*="makeanoffer-form"]',
            'css-class' => 'a[href*="makeanoffer-form"]',
            'css-hover' => 'a[href*="makeanoffer-form"]:hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'a[href*="makeanoffer-form"]',
                    'values' => array(
                        'Get e-Price',
                        'Get Internet Price',
                        'Get Our Best Price',
                        'Get Special Price',
                        'Get Current Price',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'test-drive' => [
            'url-match' => '/\\/(?:new|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[href*="schedule-form"]',
            'css-class' => 'a[href*="schedule-form"]',
            'css-hover' => 'a[href*="schedule-form"]:hover',
            'button_action' => [
                'form',
                'test-drive',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'test-drive' => [
                    'target' => 'a[href*="schedule-form"]',
                    'values' => array(
                        'Request Test Drive',
                        'Test Drive today',
                        'Want to Test Drive?',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '000000',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '222222',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '10px 0px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
],
);
