<?php

global $CronConfigs;
$CronConfigs["rvsuperstoresaskatooncom"] = array(
    "name" => " rvsuperstoresaskatooncom",
    "email" => "regan@smedia.ca",
    "password" => " rvsuperstoresaskatooncom",
    "log" => true,
    'combined_feed_mode' => true,
    "banner" => array(
        "template" => "rvsuperstoresaskatooncom",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
        "fb_lookalike_description" => "Check out this [year] [make] [model]! Click for more information.",
        "fb_dynamiclead_description" => "Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to answer any questions.",
        "old_price" => "msrp",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
),
    'lead' => array(
        'live' => false,
        'lead_type_' => true,
        'lead_type_new' => true,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#F78F1E',
            '#F78F1E',
),
        'button_color_hover' => array(
            '#FD5C01',
            '#FD5C01',
),
        'button_color_active' => array(
            '#FD5C01',
            '#FD5C01',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => '$1000 OFF in-stock models at Saskatoon RV SuperStore',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src=\\"[image]\\"/><p><br><br>Saskatoon RV SuperStore Team',
        'forward_to' => array(
            'psimpson@frankdunntoyota.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/details\\//i',
            'service' => '',
),
),
);