<?php

global $CronConfigs;
$CronConfigs["simanautosales"] = array(
    "name" => " simanautosales",
    "email" => "regan@smedia.ca",
    "password" => " simanautosales",
    'fb_brand' => '[year] [make] [model] - [body_style]',
    "log" => true,
    'max_cost' => 500,
    'cost_distribution' => array(
        'adwords' => 500,
),
    "create" => array(
        "new_search" => no,
        "used_search" => yes,
        "new_placement" => no,
        "used_placement" => yes,
        "new_display" => no,
        "used_display" => no,
        "new_retargeting" => no,
        "used_retargeting" => yes,
        "new_marketbuyers" => no,
        "used_marketbuyers" => no,
        "new_combined" => no,
        "used_combined" => yes,
),
    "new_descs" => array(
        array(
            "desc1" => "Test Drive the [year]",
            "desc2" => "[make] [model] today.",
),
        array(
            "desc1" => "Call us today about the ",
            "desc2" => "[year] [make] [model] today",
),
),
    "used_descs" => array(
        array(
            "desc1" => "Test Drive the [year]",
            "desc2" => "[make] [model] today.",
),
        array(
            "desc1" => "Call us today about the ",
            "desc2" => "[year] [make] [model] today",
),
),
    'customer_id' => '242-034-0354',
    "banner" => array(
        "template" => "simanautosales",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Siman Auto Sales may be interested in BUYING your vehicle. Contact us today for a free appraisal and inspection.",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today! Siman Auto Sales may be interested in BUYING your vehicle. Contact us today for a free appraisal and inspection.",
        "fb_dynamiclead_description" => "Are you still interested in the [year] [make] [model]? Click below and fill in your information. Our product specialist will be in touch to answer any questions.",
        "flash_style" => "default",
        "styels" => array(
            "new_display" => "dynamic_banner",
            "used_display" => "dynamic_banner",
            "new_retargeting" => "dynamic_banner",
            "used_retargeting" => "dynamic_banner",
            "new_marketbuyers" => "dynamic_banner",
            "used_marketbuyers" => "dynamic_banner",
),
        "border_color" => "#282828",
        "font_color" => "#ffffff",
),
    "lead" => array(
        'live' => true,
        'lead_type_' => true,
        'lead_type_new' => false,
        'lead_type_used' => true,
        'lead_type_service' => false,
        'shown_cap' => false,
        'fillup_cap' => false,
        'session_close' => false,
        'device_type' => array(
            'mobile' => true,
            'desktop' => true,
            'tablet' => true,
),
        'sent_client_email' => true,
        'offer_minimum_price' => 0,
        'offer_maximum_price' => 10000000,
        'bg_color' => '#EFEFEF',
        'text_color' => '#404450',
        'border_color' => '#E5E5E5',
        'button_color' => array(
            '#FF9D27',
            '#FF9D27',
),
        'button_color_hover' => array(
            '#6B9DCE',
            '#6B9DCE',
),
        'button_color_active' => array(
            '#6B9DCE',
            '#6B9DCE',
),
        'button_text_color' => '#FFFFFF',
        'response_email_subject' => 'Free Vehicle Appraisals at Siman Auto Sales',
        'response_email' => 'Hello [name],<p> Thank you for signing up for our offer. Please print this off, or show your sales professional this email on your phone to claim.</p><br><img src="[image]"/><p><br><br>Siman Auto Sales Team',
        'forward_to' => array(
            'manager@simanautosales.com',
            'sales@simanautosales.com',
            'marshal@smedia.ca',
),
        'special_to' => array(
            '',
),
        'special_email' => '',
        'display_after' => 30000,
        'retarget_after' => 5000,
        'fb_retarget_after' => 5000,
        'adword_retarget_after' => 5000,
        'visit_count' => 0,
        'video_smart_offer' => false,
        'video_smart_offer_form' => false,
        'video_url' => '',
        'video_title' => '',
        'video_description' => '',
        'lead_in' => array(
            'vdp' => '/\\/(?:new|used)\\/vehicle\\/[0-9]{4}-/i',
            'service' => '',
),
),
);