<?php

global $CronConfigs;
$CronConfigs["sptoyota"] = array(
    'password' => 'sptoyota',
    "email" => "regan@smedia.ca",
    'fb_brand' => '[year] [make] [model] - [body_style]',
    'log' => true,
    'tag_debug' => false,
    "banner" => array(
        "template" => "sptoyota",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more information.",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today! Click for more information.",
        "fb_marketplace_description" => "[description]",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
),
    'adf_to' => array(
        'leads@sherwoodparktoyota.motosnap.com',
),
    'form_live' => true,
    'button_algorithm' => 'thompson_sampling|softmax|ucb-1|default',
    'buttons_live' => true,
    'buttons' => [
        'request-a-quote' => [
            'url-match' => '/\\/inventory\\/(certified-)?(?:new|used)-[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a.button.cta-button.block.button-form.fancybox',
            'css-class' => 'a.button.cta-button.block.button-form.fancybox',
            'css-hover' => 'a.button.cta-button.block.button-form.fancybox:hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'a.button.cta-button.block.button-form.fancybox',
                    'values' => array(
                        'Get Exclusive Price',
                        'Get E-Price',
                        'Internet Price',
),
],
],
            'styles' => array(
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#086597,#086597)',
                        'border-color' => '086597',
                        'max-width' => '100%',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#188BB7,#188BB7)',
                        'border-color' => '188BB7',
                        'max-width' => '100%',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE8100,#EE8100)',
                        'border-color' => 'EE8100',
                        'max-width' => '100%',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'max-width' => '100%',
),
),
                'Cyan' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '086597',
                        'max-width' => '100%',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#0093CF,#0093CF)',
                        'border-color' => '188BB7',
                        'max-width' => '100%',
),
),
),
],
        'trade-in' => [
            'url-match' => '/\\/inventory\\/(certified-)?(?:new|used)-[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-av-button-product="tradein"]',
            'css-class' => 'a[data-av-button-product="tradein"]',
            'css-hover' => 'a[data-av-button-product="tradein"]:hover',
            'button_action' => [
                'form',
                'trade-in',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'trade-in' => [
                    'target' => 'a[data-av-button-product="tradein"]',
                    'values' => array(
                        'Value My Trade',
                        'Get Your Trade In Value',
                        'We\'ll Buy Your Car',
),
],
],
            'styles' => array(
                'Cyan' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#0093CF,#0093CF)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE8100,#EE8100)',
                        'border-color' => 'EE8100',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#086597,#086597)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#188BB7,#188BB7)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
),
],
        'financing' => [
            'url-match' => '/\\/inventory\\/(certified-)?(?:new|used)-[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-av-button-product="credit"]',
            'css-class' => 'a[data-av-button-product="credit"]',
            'css-hover' => 'a[data-av-button-product="credit"]:hover',
            'button_action' => [
                'form',
                'finance',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'financing' => [
                    'target' => 'a[data-av-button-product="credit"]',
                    'values' => array(
                        'Get Pre-Approved',
                        'Calculate Payments',
                        'Financing Options',
),
],
],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE8100,#EE8100)',
                        'border-color' => 'EE8100',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#086597,#086597)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#188BB7,#188BB7)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Cyan' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#0093CF,#0093CF)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
),
],
],
);