<?php

global $CronConfigs;
$CronConfigs["starfordstreator"] = array(
    "name" => " starfordstreator",
    "email" => "regan@smedia.ca",
    "password" => " starfordstreator",
    "log" => true,
    "banner" => array(
        "template" => "starfordstreator",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
        //			"fb_lookalike_description"	=> "Test drive the [year] [make] [model] today!",
        //			"fb_dynamiclead_description"	=> "Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to aid in any questions.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
),
    'adf_to' => array(
        'starford-lincoln@forddirectcrm.com',
),
    'form_live' => false,
    'buttons_live' => false,
    'buttons' => [
        'get-information' => [
            'url-match' => '/\\/(?:new|certified|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a.btn.btn-default.eprice.dialog.button.mm-eprice-btn',
            'css-class' => 'a.btn.btn-default.eprice.dialog.button.mm-eprice-btn',
            'css-hover' => 'a.btn.btn-default.eprice.dialog.button.mm-eprice-btn:hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-information' => [
                    'target' => 'a.btn.btn-default.eprice.dialog.button.mm-eprice-btn',
                    'values' => array(
                        'More Information',
                        'Request Information',
                        'Contact Us',
                        'Learn More',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => 'CC7500',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '00ABF1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '005C82',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '00A300',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '297A1B',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'financing' => [
            'url-match' => '/\\/(?:new|certified|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'li a.btn.btn-primary.btn-block.calculate.mm-payment-calculator-btn',
            'css-class' => 'li a.btn.btn-primary.btn-block.calculate.mm-payment-calculator-btn',
            'css-hover' => 'li a.btn.btn-primary.btn-block.calculate.mm-payment-calculator-btn:hover',
            'button_action' => [
                'form',
                'finance',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'li a.btn.btn-primary.btn-block.calculate.mm-payment-calculator-btn',
                    'values' => array(
                        'Apply For Financing',
                        'Financing Available',
                        'No Hassle Financing',
                        'Get Financed Today',
                        'Explore Payments',
                        'See Another Payment',
                        'Calculate Your Payments',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => 'CC7500',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '00ABF1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '005C82',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '00A300',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '297A1B',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'test-drive' => [
            'url-match' => '/\\/(?:new|certified|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-href*=schedule]',
            'css-class' => ' a[data-href*=schedule]',
            'css-hover' => ' a[data-href*=schedule]:hover',
            'button_action' => [
                'form',
                'test-drive',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'test-drive' => [
                    'target' => 'a[data-href*=schedule]',
                    'values' => array(
                        'Request a Test Drive',
                        'Book a Test Drive',
                        'Schedule a Test Drive',
                        'Schedule My Visit',
                        'Want to Test Drive?',
                        'Test Drive Today',
                        'Test Drive Now',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#BB0A30,#BB0A30)',
                        'border-color' => 'BB0A30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#9B0828,#9B0828)',
                        'border-color' => '9B0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#CC7500,#CC7500)',
                        'border-color' => 'CC7500',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '00ABF1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#005C82,#005C82)',
                        'border-color' => '005C82',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A300,#00A300)',
                        'border-color' => '00A300',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#297A1B,#297A1B)',
                        'border-color' => '297A1B',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
        'request-information' => [
            'url-match' => '/\\/(?:new|certified|used)\\/[^\\/]+\\/[0-9]{4}-/i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-href*=lead-form]',
            'css-class' => ' a[data-href*=lead-form]',
            'css-hover' => ' a[data-href*=lead-form]:hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-information' => [
                    'target' => 'a[data-href*=lead-form]',
                    'values' => array(
                        'Get More Information',
                        'Ask A Question',
                        'Inquire Now',
),
],
],
            'styles' => array(
                'red' => array(
                    'normal' => array(
                        'background' => '#BB0A30',
                        'border-color' => '#bb0a30',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => '#9B0828',
                        'border-color' => '#9b0828',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'orange' => array(
                    'normal' => array(
                        'background' => '#CC7500',
                        'border-color' => '#CC7500',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => '#CF540E',
                        'border-color' => '#CF540E',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => '#00ABF1',
                        'border-color' => '#00ABF1',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => '#005C82',
                        'border-color' => '#005C82',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => '#00A300',
                        'border-color' => '#00A300',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => '#297A1B',
                        'border-color' => '#297A1B',
                        'color' => '#fff',
                        'display' => 'block',
                        'float' => 'none',
                        'font-size' => '15px',
                        'font-weight' => '400',
                        'line-height' => '17px',
                        'margin' => '10px 0',
                        'padding' => '16px 10px',
                        'position' => 'relative',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
),
),
),
],
],
);