<?php

global $CronConfigs;
$CronConfigs["toyotanorthwestedmonton"] = array(
    'password' => 'toyotanorthwestedmonton',
    "email" => "regan@smedia.ca",
    'fb_brand' => '[year] [make] [model] - [body_style]',
    'log' => true,
    'tag_debug' => false,
    "banner" => array(
        "template" => "toyotanorthwestedmonton",
        "fb_description" => "Are you still interested in the [year] [make] [model]? Click for more information.",
        "fb_lookalike_description" => "Check out this [year] [make] [model] today! Click for more information.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
),
    'adf_to' => array(
        'leads@toyotanorthwestedmonton.motosnap.com',
),
    'form_live' => true,
    'button_algorithm' => 'thompson_sampling|softmax|ucb-1|default',
    'buttons_live' => true,
    'buttons' => [
        //        'request-a-quote' => [
        //            'url-match' => '/\\/new\\/[^\\/]+\\/[0-9]{4}-/i',
        //            'target' => null,
        //            //Don't move button
        //            'locations' => [
        //                'default' => null,
        //            ],
        //            'action-target' => 'a[data-href*=eprice].eprice',
        //            'css-class' => 'a[data-href*=eprice].eprice',
        //            'css-hover' => 'a[data-href*=eprice].eprice:hover',
        //            'button_action' => [
        //                'form',
        //                'e-price',
        //            ],
        //            'sizes' => [
        //                '100' => [],
        //            ],
        //            'texts' => [
        //                'request-a-quote' => [
        //                    'target' => 'a[data-href*=eprice].eprice',
        //                    'values' => array(
        //                        'Get Price Updates',
        //                        'Local Pricing',
        //                        'Best Price',
        //                        'Get Current Market Price',
        //                        'Get Internet Price Now',
        //                        'Get Your Price!',
        //                        'Get Your Exclusive Price',
        //                    ),
        //                ],
        //            ],
        //            'styles' => array(
        //                'orange' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#EE8100,#EE8100)',
        //                        'border-color' => '#ee8100',
        ////                        'width' => '215%',
        //                        //         'text-align' => 'left',
        //                        'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#CF540E,#CF540E)',
        //                        'border-color' => '#cf540e',
        ////                        'width' => '215%',
        //                        //    'text-align' => 'left',
        //                        'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'red' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#EE3000,#EE3000)',
        //                        'border-color' => '#ee3000',
        ////                        'width' => '215%',
        //                        //   'text-align' => 'left',
        //                        //      'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#C60C0D,#C60C0D)',
        //                        'border-color' => '#c60c0d',
        ////                        'width' => '215%',
        //                        // 'text-align' => 'left',
        //                        //       'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'green' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#00A84E,#00A84E)',
        //                        'border-color' => '#00a84e',
        ////                        'width' => '215%',
        //                        // 'text-align' => 'left',
        //                        //     'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#359D22,#359D22)',
        //                        'border-color' => '#359d22',
        ////                        'width' => '215%',
        //                        //  'text-align' => 'left',
        //                        //    'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'blue' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#086597,#086597)',
        //                        'border-color' => '#086597',
        ////                        'width' => '215%',
        //                        //  'text-align' => 'left',
        //                        //        'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#188BB7,#188BB7)',
        //                        'border-color' => '#188bb7',
        ////                        'width' => '215%',
        //                        //   'text-align' => 'left',
        //                        //      'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'Platinum' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#B9B099,#B9B099)',
        //                        'border-color' => '#086597',
        ////                        'width' => '215%',
        //                        //  'text-align' => 'left',
        //                        //      'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#ABA085,#ABA085)',
        //                        'border-color' => '#188bb7',
        ////                        'width' => '215%',
        //                        //  'text-align' => 'left',
        //                        //  'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'Black' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#333333,#333333)',
        //                        'border-color' => '#086597',
        ////                        'width' => '215%',
        //                        //  'text-align' => 'left',
        //                        //     'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#000000,#000000)',
        //                        'border-color' => '#188bb7',
        ////                        'width' => '215%',
        //                        // 'text-align' => 'left',
        //                        //   'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'Cyan' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
        //                        'border-color' => '#086597',
        ////                        'width' => '215%',
        //                        //   'text-align' => 'left',
        //                        //      'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#0093CF,#0093CF)',
        //                        'border-color' => '#188bb7',
        ////                        'width' => '215%',
        //                        //    'text-align' => 'left',
        //                        //                 'padding-left' => '30px',
        //                        'width' => '215%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //            ),
        //        ],
        'request-a-quote' => [
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-target="vdp-inquire-modal"]',
            'css-class' => 'a[data-target="vdp-inquire-modal"]',
            'css-hover' => 'a[data-target="vdp-inquire-modal"]:hover',
            'button_action' => [
                'form',
                'e-price',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'request-a-quote' => [
                    'target' => 'a[data-target="vdp-inquire-modal"]',
                    'values' => array(
                        'Get Exclusive Price',
                        'Get E-Price',
                        'Internet Price',
),
],
],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE8100,#EE8100)',
                        'border-color' => 'EE8100',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE3000,#EE3000)',
                        'border-color' => 'EE3000',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#C60C0D,#C60C0D)',
                        'border-color' => 'C60C0D',
                        'color' => '#fff',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A84E,#00A84E)',
                        'border-color' => '00A84E',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#359D22,#359D22)',
                        'border-color' => '359D22',
                        'color' => '#fff',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#086597,#086597)',
                        'border-color' => '086597',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#188BB7,#188BB7)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
),
),
                'Platinum' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#B9B099,#B9B099)',
                        'border-color' => '086597',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#ABA085,#ABA085)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
),
),
                'Black' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#333333,#333333)',
                        'border-color' => '086597',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#000000,#000000)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
),
),
                'Cyan' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '086597',
                        'color' => '#fff',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#0093CF,#0093CF)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
),
),
),
],
        //        'used request-a-quote' => [
        //            'url-match' => '/\\/(?:used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
        //            'target' => null,
        //            //Don't move button
        //            'locations' => [
        //                'default' => null,
        //            ],
        //            'action-target' => 'a[data-href*=eprice].eprice',
        //            'css-class' => 'a[data-href*=eprice].eprice',
        //            'css-hover' => 'a[data-href*=eprice].eprice:hover',
        //            'button_action' => [
        //                'form',
        //                'e-price',
        //            ],
        //            'sizes' => [
        //                '100' => [],
        //            ],
        //            'texts' => [
        //                'used request-a-quote' => [
        //                    'target' => 'a[data-href*=eprice].eprice',
        //                    'values' => array(
        //                        'Get Your Exclusive Price',
        //                        'Get Price Updates',
        //                        'Local Pricing',
        //                        'Best Price',
        //                        'Get Current Market Price',
        //                        'Get Internet Price Now',
        //                        'Get Your Price!',
        //                    ),
        //                ],
        //            ],
        //            'styles' => array(
        //                'orange' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#EE8100,#EE8100)',
        //                        'border-color' => 'EE8100',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#CF540E,#CF540E)',
        //                        'border-color' => 'CF540E',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'red' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#EE3000,#EE3000)',
        //                        'border-color' => 'EE3000',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#C60C0D,#C60C0D)',
        //                        'border-color' => 'C60C0D',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'green' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#00A84E,#00A84E)',
        //                        'border-color' => '00A84E',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#359D22,#359D22)',
        //                        'border-color' => '359D22',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'blue' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#086597,#086597)',
        //                        'border-color' => '086597',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#188BB7,#188BB7)',
        //                        'border-color' => '188BB7',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'Platinum' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#B9B099,#B9B099)',
        //                        'border-color' => '086597',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#ABA085,#ABA085)',
        //                        'border-color' => '188BB7',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'Black' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#333333,#333333)',
        //                        'border-color' => '086597',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#000000,#000000)',
        //                        'border-color' => '188BB7',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //                'Cyan' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
        //                        'border-color' => '086597',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#0093CF,#0093CF)',
        //                        'border-color' => '188BB7',
        //                        'width' => '100%',
        //                        'text-align' => 'center',
        //                    ),
        //                ),
        //            ),
        //        ],
        //        'request-information' => [
        //            'url-match' => '/\\/(?:new|used|certified)\\/[^\\/]+\\/[0-9]{4}-/i',
        //            'target' => null,
        //            //Don't move button
        //            'locations' => [
        //                'default' => null,
        //            ],
        //            'action-target' => 'a[href*=vehiclelead]',
        //            'css-class' => 'a[href*=vehiclelead]',
        //            'css-hover' => 'a[href*=vehiclelead]:hover',
        //            'button_action' => [
        //                'form',
        //                'e-price',
        //            ],
        //            'sizes' => [
        //                '100' => [],
        //            ],
        //            'texts' => [
        //                'request-information' => [
        //                    'target' => 'a[href*=vehiclelead]',
        //                    'values' => array(
        //                        'Get More Details',
        //                        'More Info',
        //                        'Ask an Expert!',
        //                        'Ask a Question!',
        //                        'Confirm Availability',
        //                    ),
        //                ],
        //            ],
        //            'styles' => array(
        //                'orange' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#EE8100,#EE8100)',
        //                        'border-color' => 'EE8100',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#CF540E,#CF540E)',
        //                        'border-color' => 'CF540E',
        //                    ),
        //                ),
        //                'red' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#EE3000,#EE3000)',
        //                        'border-color' => 'EE3000',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#C60C0D,#C60C0D)',
        //                        'border-color' => 'C60C0D',
        //                    ),
        //                ),
        //                'green' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#00A84E,#00A84E)',
        //                        'border-color' => '00A84E',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#359D22,#359D22)',
        //                        'border-color' => '359D22',
        //                    ),
        //                ),
        //                'blue' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#086597,#086597)',
        //                        'border-color' => '086597',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#188BB7,#188BB7)',
        //                        'border-color' => '188BB7',
        //                    ),
        //                ),
        //                'Platinum' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#B9B099,#B9B099)',
        //                        'border-color' => '086597',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#ABA085,#ABA085)',
        //                        'border-color' => '188BB7',
        //                    ),
        //                ),
        //                'Black' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#333333,#333333)',
        //                        'border-color' => '086597',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#000000,#000000)',
        //                        'border-color' => '188BB7',
        //                    ),
        //                ),
        //                'Cyan' => array(
        //                    'normal' => array(
        //                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
        //                        'border-color' => '086597',
        //                    ),
        //                    'hover' => array(
        //                        'background' => 'linear-gradient(#0093CF,#0093CF)',
        //                        'border-color' => '188BB7',
        //                    ),
        //                ),
        //            ),
        //        ],
        'trade-in' => [
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-av-button-product="tradein"]',
            'css-class' => 'a[data-av-button-product="tradein"]',
            'css-hover' => 'a[data-av-button-product="tradein"]:hover',
            'button_action' => [
                'form',
                'trade-in',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'trade-in' => [
                    'target' => 'a[data-av-button-product="tradein"]',
                    'values' => array(
                        'Value My Trade',
                        'Get Your Trade In Value',
                        'We\'ll Buy Your Car',
),
],
],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE8100,#EE8100)',
                        'border-color' => 'EE8100',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE3000,#EE3000)',
                        'border-color' => 'EE3000',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#C60C0D,#C60C0D)',
                        'border-color' => 'C60C0D',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A84E,#00A84E)',
                        'border-color' => '00A84E',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#359D22,#359D22)',
                        'border-color' => '359D22',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#086597,#086597)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#188BB7,#188BB7)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Platinum' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#B9B099,#B9B099)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#ABA085,#ABA085)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Black' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#333333,#333333)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#000000,#000000)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Cyan' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#0093CF,#0093CF)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
),
],
        'financing' => [
            'url-match' => '/\\/vehicles\\/[0-9]{4}\\//i',
            'target' => null,
            //Don't move button
            'locations' => [
                'default' => null,
],
            'action-target' => 'a[data-av-button-product="credit"]',
            'css-class' => 'a[data-av-button-product="credit"]',
            'css-hover' => 'a[data-av-button-product="credit"]:hover',
            'button_action' => [
                'form',
                'finance',
],
            'sizes' => [
                '100' => [],
],
            'texts' => [
                'financing' => [
                    'target' => 'a[data-av-button-product="credit"]',
                    'values' => array(
                        'Get Pre-Approved',
                        'Calculate Payments',
                        'Financing Options',
),
],
],
            'styles' => array(
                'orange' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE8100,#EE8100)',
                        'border-color' => 'EE8100',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#CF540E,#CF540E)',
                        'border-color' => 'CF540E',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'red' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#EE3000,#EE3000)',
                        'border-color' => 'EE3000',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#C60C0D,#C60C0D)',
                        'border-color' => 'C60C0D',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'green' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00A84E,#00A84E)',
                        'border-color' => '00A84E',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#359D22,#359D22)',
                        'border-color' => '359D22',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'blue' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#086597,#086597)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#188BB7,#188BB7)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Platinum' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#B9B099,#B9B099)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#ABA085,#ABA085)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Black' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#333333,#333333)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#000000,#000000)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
                'Cyan' => array(
                    'normal' => array(
                        'background' => 'linear-gradient(#00ABF1,#00ABF1)',
                        'border-color' => '086597',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
                    'hover' => array(
                        'background' => 'linear-gradient(#0093CF,#0093CF)',
                        'border-color' => '188BB7',
                        'color' => '#fff',
                        'text-align' => 'center',
                        'display' => 'block',
                        'float' => 'none',
                        'font-family' => 'Raleway, arial, sans-serif',
                        'font-size' => '14px',
                        'font-weight' => '700',
                        'line-height' => '17px',
                        'margin' => '10px 0 0',
                        'padding' => '9px 10px',
                        'position' => 'relative',
                        'text-decoration' => 'none',
),
),
),
],
],
);