<?php
global $CronConfigs;
 $CronConfigs["westsidesales"] = array( 
	"name"  =>" westsidesales",
	"email" => "regan@smedia.ca",
	"password" =>" westsidesales", 'fb_brand'          => '[year] [make] [model] - [body_style]',
	"log" => true ,
	"banner" => array(
        "template" => "westsidesales",
			"fb_description" => "Are you still interested in the [year] [make] [model]? Click for more info!",
			"fb_lookalike_description"	=> "Check out this [year] [make] [model]! Click for more information.",
			//"fb_dynamiclead_description"	=> "Are you still interested in the [year] [make] [model]? Click below, fill in your info, and a product specialist will be in touch to answer any questions.",
        "flash_style" => "default",
        "border_color" => "#282828",
        "font_color" => "#ffffff",
    ),
	"lead"  => array(
		'live'                  => false,
		'lead_type_'            => true,
		'lead_type_new'         => true,
		'lead_type_used'        => true,
		'bg_color'              => "#efefef",
		'text_color'            => "#404450",
		'border_color'          => "#e5e5e5",
		'button_color'          => array("#dbb13b", "#dbb13b"),
		'button_color_hover'    => array("#414141", "#414141"),
		'button_color_active'   => array("#414141", "#414141"),
		'button_text_color'     => "#ffffff",
		'response_email_subject'=> "$200 OFF coupon from Westside Sales",
		'response_email'        => "Hello [name],<p> Please print this off or show your sales professional this email on your phone to claim.</p><br><img src=\"[image]\"/><p><br><br>Westside Sales Team",
		'forward_to'            => array("cliffroulston@shaw.ca","marshal@smedia.ca","nanang@smedia.ca"),
		'respond_from'          => "offers@mail.smedia.ca",
		'forward_from'          => "offers@mail.smedia.ca",
		'thank_you'             => "<h1 style=\"margin: 100px 27px; text-align: center;\">Thank you</h1>",
	),
);