<?php

// Web Providers
$smedia_website_providers = [
    'foxdealer'              => '/.*foxdealer\.com.*/i', // foxdealer.com
    'vinads'                 => '/.*vinads\.com.*/i', // vinads.com
    'amcreative'             => '/.*amcreative\.com.*/i', // amcreative.com
    'aftens'                 => '/.*aftens\.com.*/i', // aftens.com
    'dealrcloud'             => '/.*dealrcloud\.com.*/i', // dealrcloud.com
    'dealrcloud'             => '/.*dealr\.cloud.*/i', // dealr.cloud
    'dealerscloud'           => '/.*dealerscloud\.com.*/i', // dealerscloud.com
    'northtxautos'           => '/.*northtxautos\.com.*/i', // northtxautos.com
    'carguywebdesign'        => '/.*carguywebdesign\.com.*/i', // carguywebdesign.com
    'pcswebdesign'           => '/.*pcswebdesign\.com.*/i', // pcswebdesign.com
    'autocorner'             => '/.*autocorner\.com.*/i', // AutoCorner.com
    'zopdealer'              => '/.*zopdealer\.com.*/i', // zopdealer.com
    'luminary2'              => '/.*luminary2\.com.*/i', // luminary2.com
    'itjames'                => '/.*itjames\.com.*/i', // itjames.com
    'edealer'                => '/.*edealer\.ca.*/i', // edealer.ca
    'autodealertech'         => '/.*autodealertech\.co.*/i', // autodealertech.co
    'autodealertech'         => '/.*automotivedealertech\.com.*/i', // automotivedealertech.com
    'autodatasolutions'      => '/.*autodatasolutions\.com.*/i', // autodatasolutions.com
    'autodatadirect'         => '/.*autodatadirect\.com.*/i', // autodatadirect.com
    'autowebexpress'         => '/.*autowebexpress\.com.*/i', // autowebexpress.com
    'dealer'                 => '/.*\.dealer\.com.*/i', // dealer.com
    'areacars'               => '/.*areacars\.com.*/i', // areacars.com
    'dealermc'               => '/.*dealermc\.com.*/i', // dealermc.com
    'blackbmedia'            => '/.*blackbmedia\.com.*/i', // blackbmedia.com
    'autoaubaine'            => '/.*autoaubaine\.com.*/i', // autoaubaine.com
    'autotrader'             => '/.*\/tadvantage-logos\/.*/i', // autotrader.ca
    'dealersiteplus'         => '/.*dealersiteplus.*/i', // dealersiteplus.ca
    'westoffour'             => '/.*westoffour\.com.*/i', // westoffour.com
    'dillonstienike'         => '/.*dillonstienike\.com.*/i', // dillonstienike.com
    'autoshotservices'       => '/.*autoshotservices\.com.*/i', // autoshotservices.com
    'autolinkme'             => '/.*autolinkme\.com.*/i', // autolinkme.com
    'orcasitetech'           => '/.*orcasitetech\.com.*/i', // orcasitetech.com
    'yourcarlot'             => '/.*yourcarlot\.com.*/i', // yourcarlot.com
    'dealerclick'            => '/.*dealerclick\.com.*/i', // dealerclick.com
    'cdkglobal'              => '/.*cdk\.com.*/i', // cdkglobal.com
    'dealerinspire'          => '/.*dealerinspire\.com.*/i', // dealerinspire.com
    'dealerspike'            => '/.*dealerspike\.com.*/i', // dealerspike.com
    'strathcom'              => '/.*strathcom\.com.*/i', // strathcom.com
    'convertus'              => '/.*convertus\.com.*/i', // convertus.com
    'ipssolutions'           => '/.*ipssolutions\.com.*/i', // ipssolutions.com
    'ipssolutions'           => '/.*greenbaywebdesigncompany\.com.*/i', // greenbaywebdesigncompany.com    // same as ipssolutions
    'webxloo'                => '/.*webxloo\.com.*/i', // webxloo.com
    'redknight'              => '/.*redknight\.com.*/i', // redknight.com
    'gorillathemes'          => '/.*gorillathemes\.com.*/i', // gorillathemes.com
    'redxwebdesign'          => '/.*redxwebdesign\.com.*/i', // redxwebdesign.com
    'autoadmanager'          => '/.*autoadmanager\.com.*/i', // autoadmanager.com
    'chrsinteractive'        => '/.*chrsinteractive\.com.*/i', // chrsinteractive.com
    'goxeedealer'            => '/.*goxeedealer\.com.*/i', // goxeedealer.com
    'gstockco'               => '/.*gstockco\.com.*/i', // gstockco.com
    'autosearchtech'         => '/.*autosearchtech\.com.*/i', // autosearchtech.com
    'carthink'               => '/.*carthink\.com.*/i', // carthink.com
    'dealereprocess'         => '/.*dealereprocess\.org.*/i', // dealereprocess.org
    'forddirect'             => '/.*forddirect\.com.*/i', // forddirect.com
    'midealervirtual'        => '/.*midealervirtual\.com.*/i', // midealervirtual.com
    'autopublishers'         => '/.*autopublishers\.com.*/i', // autopublishers.com
    'shiftpointsolution'     => '/.*shiftpointsolution\.com.*/i', // shiftpointsolution.com
    'seoadvantage'           => '/.*seoadvantage\.com.*/i', // seoadvantage.com
    'dealeron'               => '/.*dealeron\.com.*/i', // dealeron.com
    'majux'                  => '/.*majux\.com.*/i', // majux.com
    'vinlist'                => '/.*vinlist\.com.*/i', // vinlist.com
    'mach20autos'            => '/.*mach20autos\.com.*/i', // mach20autos.com
    'finalcom'               => '/.*finalcom\.net.*/i', // finalcom.net
    'webtechs'               => '/.*webtechs\.net.*/i', // webtechs.net
    'dealerseo'              => '/.*dealerseo\.net.*/i', // dealerseo.net
    'dealerseo'              => '/.*stevetackett\.com.*/i', // stevetackett.com    // same as dealerseo
    'dealerseo'              => '/.*dealerleads\.com\/dealer-seo.*/i', // stevetackett.com    // same as dealerseo
    'optiauto'               => '/.*optiauto\.net.*/i', // optiauto.net
    'autosalesweb'           => '/.*autosalesweb\.net.*/i', // autosalesweb.net
    'sm360'                  => '/.*sm360\.ca.*/i', // sm360.ca
    'inv360'                 => '/.*inv360\.app/i', // inv360.app
    '360agency'              => '/.*360\.agency.*/i', // 360.agency
    'dealercarsearch'        => '/.*dealercarsearch\.com.*/i', // dealercarsearch.com
    'psone'                  => '/.*psone\.ca.*/i', // psone.ca
    'dealerdirect'           => '/.*dealerdirect\.eu.*/i', // dealerdirect.eu
    'fzautomotive'           => '/.*fzautomotive\.com.*/i', // fzautomotive.com
    'rndinteractive'         => '/.*rndinteractive\.com.*/i', // rndinteractive.com
    'autorevo'               => '/.*autorevo\.com.*/i', // autorevo.com
    'nissanusa'              => '/.*nissanusa\.com.*/i', // nissanusa.com
    'dealerfire'             => '/.*dealerfire\.com.*/i', // dealerfire.com
    'autosweet'              => '/.*autosweet\.com.*/i', // autosweet.com
    'dealerx'                => '/.*dealerx\.com.*/i', // dealerx.com
    'chromacars'             => '/.*chromacars\.com.*/i', // chromacars.com
    'mindspank'              => '/.*mindspank\.com.*/i', // mindspank.com
    'autoconx'               => '/.*autoconx\.com.*/i', // autoconx.com
    'automanager'            => '/.*automanager\.com.*/i', // automanager.com
    'psmmarketing'           => '/.*psmmarketing\.com.*/i', // psmmarketing.com
    'higherturnover'         => '/.*higherturnover\.com.*/i', // higherturnover.com
    'slipstream'             => '/.*slipstreamcreative\.com.*/i', // slipstreamcreative.com
    'maverickmultimedia'     => '/.*maverickmultimedia\.com.*/i', // maverickmultimedia.com
    'localsearchmagic'       => '/.*localsearchmagic\.com.*/i', // localsearchmagic.com
    'carsforsale'            => '/.*carsforsale\.com.*/i', // carsforsale.com
    'carbase'                => '/.*carbase\.com.*/i', // carbase.com
    'dealercenter'           => '/.*dealercenter\.com.*/i', // dealercenter.com
    'tailbase'               => '/.*tailbase\.com.*/i', // tailbase.com
    'interactrv'             => '/.*interactrv\.com.*/i', // interactrv.com
    'd2cmedia'               => '/.*d2cmedia\.ca.*/i', // d2cmedia.ca
    'd2cmedia'               => '/.*d2cmedia\.com.*/i', // d2cmedia.com
    'd2cmedia'               => '/.*evolio\.ca.*/i', // evolio.ca
    'arinet'                 => '/.*arinet\.com.*/i', // arinet.com
    'passinglane'            => '/.*passinglane\.com.*/i', // passinglane.com
    'southfire'              => '/.*southfire\.com.*/i', // southfire.com
    'teamwilletts'           => '/.*teamwilletts\.com.*/i', // teamwilletts.com
    'cahillwebstudio'        => '/.*cahillwebstudio\.com.*/i', // cahillwebstudio.com
    'autocorner'             => '/.*autocorner\.com.*/i', // autocorner.com
    'Sokal'                  => '/.*gosokal\.com.*/i', // sokal.com
    'dealerfront'            => '/.*dealerfront.*/i', // dealerfront
    'waynereaves'            => '/.*waynereaves\.com.*/i', // waynereaves.com
    'arvigmedia'             => '/.*arvigmedia\.com.*/i', // arvigmedia.com
    'autoxplorer'            => '/.*autoxplorer\.com.*/i', // autoxplorer.com
    'vehiclesnetwork'        => '/.*vehiclesnetwork\.com.*/i', // vehiclesnetwork.com
    'automatrix'             => '/.*automatrix\.com.*/i', // automatrix.com
    'jtzenterprise'          => '/.*jtzenterprise\.com.*/i', // jtzenterprise.com
    'teamvelocity'           => '/.*teamvelocitymarketing\.com.*/i', // teamvelocitymarketing.com
    'topmarketingagency'     => '/.*topmarketingagency\.com.*/i', // topmarketingagency.com
    'advancedauto'           => '/.*advancedautodealers\.com.*/i', // advancedautodealers.com
    'alaskasearch'           => '/.*alaskasearchmarketing\.com.*/i', // alaskasearchmarketing.com
    'damascoinnovations'     => '/.*damascoinnovations\.com.*/i', // damascoinnovations.com
    'ezresults'              => '/.*ez-results\.ca.*/i', // EzResults.ca
    'searchoptics'           => '/.*searchoptics.*/i', // searchoptics.net or .com
    'dealerbible'            => '/.*dealerbible\.com.*/i', // dealerbible.com
    'dealersync'             => '/.*dealersync\.com.*/i', // dealersync.com
    'lotwizard'              => '/.*lotwizard\.com.*/i', // lotwizard.com
    'carcasm'                => '/.*carcasm\.com.*/i', // carcasm.com
    'dealervenom'            => '/.*dealervenom\.com.*/i', // dealervenom.com
    'surgemetrix'            => '/.*surgemetrix\.com.*/i', // surgemetrix.com
    'nakedlime'              => '/.*nakedlime\.com.*/i', // nakedlime.com
    'autofusion'             => '/.*autofusion\.com.*/i', // autofusion.com
    'jazelauto'              => '/.*jazelauto\.com.*/i', // jazelauto.com
    'pixelmotion'            => '/.*pixelmotiondemo\.com.*/i', // pixelmotiondemo.com
    'remora'                 => '/.*remora\.com.*/i', // remora.com
    '321ignition'            => '/.*321ignition\.com.*/i', // 321ignition.com
    'steeringinnovation'     => '/.*steeringinnovation\.com.*/i', // steeringinnovation.com
    'sterlingemarketing'     => '/.*sterlingemarketing\.com.*/i', // sterlingemarketing.com
    'nabthat'                => '/.*nabthat\.com.*/i', // nabthat.com
    'indigimar'              => '/.*indigimar\.com.*/i', // indigimar.com
    'fullthrottle'           => '/.*fullthrottle\.ai.*/i', // fullthrottle.ai
    'driverseat'             => '/.*driverseat\.io.*/i', // driverseat.io
    'v12soft'                => '/.*v12soft\.com.*/i', // v12soft.com
    'gammastream'            => '/.*gamma\.stream.*/i', // gamma.stream
    'baschsolutions'         => '/.*baschsolutions\.com.*/i', // baschsolutions.com
    'digisphere'             => '/.*digispheremarketing\.com.*/i', // digispheremarketing.com
    'marketmastersmedia'     => '/.*marketmastersmedia\.com.*/i', // marketmastersmedia.com
    'trafficcontrol'         => '/.*trafficcontrolmarketing\.com.*/i', // trafficcontrolmarketing.com
    'kgi'                    => '/.*dealersolutionssoftware\.com.*/i', // dealersolutionssoftware.com
    'autodealer'             => '/.*autodealerwebsiteproviders\.com.*/i', // autodealerwebsiteproviders.com
    'stevendigital'          => '/.*stevendigital\.com.*/i', // stevendigital.com
    'promax'                 => '/.*promaxunlimited\.com.*/i', // promaxunlimited.com
    'allautonetwork'         => '/.*allautonetwork\.com.*/i', // allautonetwork.com
    'westadvertising'        => '/.*westadvertising\.com.*/i', // westadvertising.com
    'inshoremarketing'       => '/.*inshoremarketing\.com.*/i', // inshoremarketing.com
    'mannainteractive'       => '/.*mannainteractive\.com.*/i', // mannainteractive.com
    'level5advertising'      => '/.*level5advertising\.com.*/i', // level5advertising.com
    'datamomentum'           => '/.*datamomentum\.com.*/i', // datamomentum.com
    'dealerslink'            => '/.*dealerslink\.com.*/i', // dealerslink.com
    'motorlot'               => '/.*motorlot\.com.*/i', // motorlot.com
    'ebizautos'              => '/.*ebizautos\.com.*/i', // ebizautos.com
    'autowall'               => '/.*gratistech\.com.*/i', // gratistech.com
    'roadster'               => '/.*roadster\.com.*/i', // roadster.com
    'crmsuite'               => '/.*crmsuite\.com.*/i', // crmsuite.com
    'usagnet'                => '/.*usagnet\.com.*/i', // usagnet.com
    'advp'                   => '/.*advp\.com.*/i', // advp.com
    'idweb'                  => '/.*idweb\.io.*/i', // idweb.io
    'autofunds'              => '/.*autofunds\.com.*/i', // autofunds.com
    'asnsoftware'            => '/.*asnsoftware\.com.*/i', // asnsoftware.com
    'motionfuze'             => '/.*motionfuze\.com.*/i', // motionfuze.com
    'datgate'                => '/.*datgate\.com.*/i', // datgate.com
    'leadbox'                => '/.*leadboxhq\.com.*/i', // leadboxhq.com
    'autojini'               => '/.*autojini\.com.*/i', // autojini.com
    'autowebing'             => '/.*autowebing\.com.*/i', // autowebing.com
    'dealerwebsites'         => '/.*dealerwebsites\.com.*/i', // dealerwebsites.com
    'speeddigital'           => '/.*speeddigital\.com.*/i', // speeddigital.com
    'dealergeek'             => '/.*dealergeek.*/i', // dealergeek.com
    'dealergreek'            => '/.*\/images\/dealer-greek-logo\.png/i', // dealergreek.com
    'terrostar'              => '/.*terrostar\.com.*/i', // terrostar.com
    'novosteer'              => '/.*novosteer\.com.*/i', // novosteer.com
    'dealerjump'             => '/.*dealerjump\.com.*/i', // dealerjump.com
    'treasuredata'           => '/.*treasuredata\.com.*/i', // treasuredata.com
    'flexdealer'             => '/.*flexdealer\.com.*/i', // flexdealer.com
    'standish'               => '/.*standish\.ca.*/i', // standish.ca
    'magnetis'               => '/.*magnetis\.ca.*/i', // magnetis.ca
    'carfire'                => '/.*carfire\.ca.*/i', // carfire.ca
    'verteb'                 => '/.*verteb\.ca.*/i', // verteb.ca
    'bwebauto'               => '/.*bwebauto\.ca.*/i', // bwebauto.ca
    'autobunny'              => '/.*autobunnydealersolutions\.ca.*/i', // autobunnydealersolutions.ca
    'godaddy'                => '/.*godaddy\.com\/websites\/web-design.*/i', // godaddy.com
    'digitalarmyrangers'     => '/.*\/company\/digital-army-rangers.*/i', // digitalarmyrangers
    'motorcentral'           => '/.*motorcentral\.co\.nz.*/i', // motorcentral.co.nz
    'sincro'                 => '/.*sincro.*/i', // https://www.sincrodigital.com
    'commandbase'            => '/.*commandbase\.ca.*/i', // https://commandbase.ca
    'dx1'                    => '/.*dx1app\.com.*/i', // https://www.dx1app.com
    'tadvantage'             => '/.*tadvantagewebsites.*/i', // https://www.dx1app.com
    'omnionline'             => '/.*omnionline\.net.*/i', // https://omnionline.net
    'focusrv'                => '/.*focusrv\.com.*/i', // https://www.focusrv.com
    'vervocity'              => '/.*vervocity\.io.*/i', // https://vervocity.io
    'branduagency'           => '/.*branduagency\.ca.*/i', // https://www.branduagency.ca
    'chromedata'             => '/.*chromelogo\.ca.*/i', // https://www.autodatasolutions.com
    'morillian'              => '/.*room58\.com.*/i', // https://room58.com/m-bws
    'alt-design'             => '/.*alt\-design\.net.*/i', // https://www.alt-design.net
    'wp-rocket'              => '/.*wp\-rocket\.me.*/i', // https://wp-rocket.me
    'webs'                   => '/.*websimages\.com.*/i', // https://www.webs.com
    'realestatewebmasters'   => '/.*realestatewebmasters\.com.*/i', // https://www.realestatewebmasters.com
    'cpgmedia'               => '/.*cpgmedia\.ca.*/i', // https://www.cpgmedia.ca
    'digitalbrain'           => '/.*digitalbrain\.ca.*/i', // https://digitalbrain.ca
    'squareflo'              => '/.*squareflo\.com.*/i', // https://squareflo.com
    'codewordmediadesign'    => '/.*codewordmediadesign\.com.*/i', // https://codewordmediadesign.com
    'squarespace'            => '/.*squarespace\.com.*/i', // https://squarespace.com
    'wix'                    => '/.*wix\.com.*/i', // https://wix.com
    'weebly'                 => '/.*weebly\.com.*/i', // https://weebly.com
    'themesuite'             => '/.*themesuite\.com.*/i', // https://themesuite.com
    'vnexttech'              => '/.*vnexttech\.com.*/i', // https://vnexttech.com
    'dealersolutions'        => '/.*dealersolutions\.com\.au.*/i', // https://dealersolutions.com.au
    'powersporttechnologies' => '/.*powersporttechnologies\.com.*/i', // https://powersporttechnologies.com
    'zopdealer'              => '/.*zopdealer\.com.*/i', // https://zopdealer.com
    'osiminteractive'        => '/.*osiminteractive\.com.*/i', // https://zopdealer.com
    'boldgrid'               => '/.*boldgrid\.com.*/i', // https://boldgrid.com
    'i-motor'                => '/.*i\-motor\.com\.au.*/i', // https://www.i-motor.com.au
    'turnkeywebsolutions'    => '/.*turnkeywebsolutions\.com.*/i', // https://www.turnkeywebsolutions.com
    'geeksonthebeach'        => '/.*geeksonthebeach\.ca.*/i', // https://www.geeksonthebeach.ca
    'evolvemedia'            => '/.*evolvemedia\.ca.*/i', // https://www.evolvemedia.ca
    'adleverage'             => '/.*adleverage\.com.*/i', // https://www.adleverage.com
    'revolutionparts'        => '/.*revolutionparts\.com.*/i', // https://www.revolutionparts.com
]; // 221

// Trade Tool Providers
$smedia_trade_providers = [
    'TradeVue'          => '/.*tradevue.*/i',
    'TradeGauge'        => '/.*drivecarma\.ca\/.*/i',
    'Edmunds'           => '/.*edmunds.*/i', // Owned by kelly blue book
    'Tradesii'          => '/.*tradesii\.com\/.*/i',
    'Accutrade'         => '/.*accu\-trade\.com\/.*/i',
    'TradeRev'          => '/.*traderev\.com\/.*/i',
    'TradePending'      => '/.*tradepending.*/i', // Owned by kelly blue book
    'KellyBlueBook'     => '/.*kbb\.com\/.*/i',
    'TrueCarTrade'      => '/.*truecar.*/i',
    'CarNow'            => '/.*carnow\.com\/.*/i',
    'carnowdealerkey'   => '/.*carnowdealerkey.*/i',
    'DealerGears'       => '/.*dealergears\.com\/.*/i',
    'AutoNation'        => '/.*autonation\.com\/.*/i',
    'Vauto'             => '/.*vauto\.com\/.*/i',
    'Autolist'          => '/.*autolist\.com\/.*/i',
    'Instamotor'        => '/.*instamotor\.com\/.*/i',
    'CarMax'            => '/.*carmax\.com\/.*/i',
    'Cars'              => '/.*\.cars\.com\/.*/i',
    'Dealertrackcanada' => '/.*dealertrackcanada\.com\/.*/i',
    'Autotrader'        => '/.*autotrader\.ca.*/i',
    'Guaranteedtrade'   => '/.*guaranteedtrade\.com.*/i',
    'Xchangevalue'      => '/.*xchangevalue\.com.*/i',
    'Tradeinvalet'      => '/.*tradeinvalet\.com.*/i',
    'YogaCars'          => '/.*yogaCarsConfig.*/i',
    'BlackBook'         => '/.*blackbook.*/i',
    'Roadster'          => '/.*roadster\.com.*/i',
    'Purecars'          => '/.*purecars\.com.*/i',
    'MaxAllowance'      => '/.*maxallowance\.com.*/i',
    'Carfax'            => '/.*cfctradein.*/i', // Owned by autotrader
    'Autoverify'        => '/.*autoverify\.com\/.*/i',
]; // 30

// Car Chat Providers
$smedia_carchat_providers = [
    'gubagootracking'      => '/.*gubagootracking\.com\/.*/i',
    'gubagoo'              => '/.*gubagoo.*/i',
    'carchat24'            => '/.*carchat24\.com\/.*/i',
    'liveadmins'           => '/.*thelivechatsoftware\.com\/.*/i',
    'liveadmins'           => '/.*liveadmins\.com\/.*/i',
    'liveguidechat'        => '/.*liveguidechat\.com\/.*/i',
    'ngagelive'            => '/.*ngagelive\.com\/.*/i',
    'livehelpnow'          => '/.*livehelpnow\.net\/.*/i',
    'chaport'              => '/.*chaport\.com\/.*/i',
    'livechatagent'        => '/.*livechatagent\.com\/.*/i',
    'livepersonautomotive' => '/.*livepersonautomotive\.com\/.*/i',
    'liveperson'           => '/.*liveperson\.com\/.*/i',
    'userlike'             => '/.*userlike\.com\/.*/i',
    'saleschat'            => '/.*saleschat\.co\/.*/i',
    'carcasm'              => '/.*carcasm\.com\/.*/i',
    'vee24'                => '/.*vee24\.com\/.*/i',
    'livechat'             => '/.*livechat\.com\/.*/i',
    'revechat'             => '/.*revechat\.com\/.*/i',
    'rvchat'               => '/.*rvchat\.com\/.*/i',
    'crisp'                => '/.*crisp\.chat\/.*/i',
    'tawk'                 => '/.*tawk\.to\/.*/i',
    'rapidrtc'             => '/.*dmt\.global\/.*/i',
]; //22

// Other Vendors
$smedia_other_providers = [
    'gtag'                     => '/.*googletagmanager\.com.*/i',
    'ganalytics'               => '/.*google\-analytics\.com.*/i',
    'gstatic'                  => '/.*gstatic\.com.*/i',
    'googleapis'               => '/.*googleapis\.com.*/i',
    'google'                   => '/.*google\.com.*/i',
    'googleadservices'         => '/.*googleadservices.com.*/i',
    'facebook'                 => '/.*facebook.*/i',
    'twitter'                  => '/.*twitter.*/i',
    'linkedin'                 => '/.*linkedin.*/i',
    'youtube'                  => '/.*youtube.*/i',
    'reddit'                   => '/.*reddit.*/i',
    'yahoo'                    => '/.*yahoo\.com.*/i',
    'cloudflare'               => '/.*cloudflare.*/i',
    'cloudfront'               => '/.*cloudfront.*/i',
    'sincrodigital'            => '/.*cobalt\.com.*/i',
    'cobaltgroup'              => '/.*cobaltgroup\.com.*/i',
    'astutesolutions'          => '/.*iperceptions\.com.*/i',
    'quantcast'                => '/.*quantserve.com.*/i',
    'xandr'                    => '/.*adnxs\.com.*/i',
    'marchex'                  => '/.*marchex\.io.*/i',
    'thetradedesk'             => '/.*adsrvr\.org.*/i',
    'spincar'                  => '/.*spincar\.com.*/i',
    'spincar'                  => '/.*swipetospin\.com.*/i',
    'tapad'                    => '/.*tapad\.com.*/i',
    'rubiconproject'           => '/.*rubiconproject\.com.*/i',
    'magnite'                  => '/.*magnite\.com.*/i',
    'bing'                     => '/.*bing\.com.*/i',
    'adobedtm'                 => '/.*adobedtm\.com.*/i',
    'clickcease'               => '/.*clickcease\.com.*/i',
    'hotjar'                   => '/.*hotjar\.com.*/i',
    'getclicky'                => '/.*getclicky\.com.*/i',
    'addtoany'                 => '/.*addtoany\.com.*/i',
    'newrelic'                 => '/.*newrelic\.com.*/i',
    'callrail'                 => '/.*callrail\.com.*/i',
    'smedia'                   => '/.*tm\.smedia\.ca.*/i',
    'mapbox'                   => '/.*mapbox\.com.*/i',
    'acsbapp'                  => '/.*acsbapp\.com.*/i',
    'generalmotorscorporation' => '/.*generalmotorscorporation.*/i',
    'azureedge'                => '/.*azureedge\.net.*/i',
    'azurefd'                  => '/.*azurefd\.net.*/i',
    'clarity'                  => '/.*clarity\.ms.*/i',
    'aws'                      => '/.*amazonaws\.com.*/i',
    'unpkg'                    => '/.*unpkg\.com.*/i',
    'trackcmp'                 => '/.*trackcmp\.com.*/i',
    'stackadapt'               => '/.*stackadapt\.com.*/i',
    'samba tv'                 => '/.*samba\.tv.*/i',
    'criteo'                   => '/.*criteo\.com.*/i',
    'polyfill'                 => '/.*polyfill.io.*/i',
    'jsdelivr'                 => '/.*jsdelivr\.com.*/i',
    'flickfusion'              => '/.*flickfusion.*/i',
    'aspnetcdn'                => '/.*aspnetcdn\.com.*/i',
    'engagetosell'             => '/.*engagetosell\.com.*/i',
    'addthis'                  => '/.*addthis\.com.*/i',
    'matador'                  => '/.*matador\.ai.*/i',
    'calltrk'                  => '/.*calltrk\.com.*/i',
    'livechatinc'              => '/.*livechatinc\.com.*/i',
    'segment'                  => '/.*segment\.com.*/i',
    'typekit'                  => '/.*typekit\.net.*/i',
    'kenshoo'                  => '/.*(?:xg4ken|kenshoo)\.com.*/i',
    'dealer-leads'             => '/.*dealer\-leads\.ca.*/i',
    'addthisedge'              => '/.*addthisedge\.com.*/i',
    'klaviyo'                  => '/.*klaviyo\.com.*/i',
    'alpixtrack'               => '/.*alpixtrack\.com.*/i',
    'foursixty'                => '/.*foursixty\.com.*/i',
    'gorgias'                  => '/.*\.gorgias\..*/i',
    'tidio'                    => '/.*tidio\.co.*/i',
    'stamped'                  => '/.*stamped\.(?:io|com).*/i',
    'searchspring'             => '/.*searchspring.net.*/i',
    'twimg'                    => '/.*twimg\.com.*/i',
    'lotlinx'                  => '/.*lotlinx\.com.*/i',
    'callmeasurement'          => '/.*callmeasurement\.com.*/i',
    'audioeye'                 => '/.*audioeye\.com.*/i',
    'ubembed'                  => '/.*ubembed\.com.*/i',
    'jquery'                   => '/.*jquery\.com.*/i',
    'bootstrap'                => '/.*bootstrap.*/i',
    'fontawesome'              => '/.*fontawesome.*/i',
    'yandex'                   => '/.*yandex\.ru.*/i',
    'rewhosting'               => '/.*rewhosting\.com.*/i',
    'quantcount'               => '/.*quantcount\.com.*/i',
    'mixpanel'                 => '/.*(?:mxpnl|mixpanel)\.com.*/i',
    'quantcount'               => '/.*quantcount\.com.*/i',
    'clarivoy'                 => '/.*clarivoy\.com.*/i',
    'vinlens'                  => '/.*vinlens\.com.*/i',
    'vinnauto'                 => '/.*vinnauto\.com.*/i',
    'calldrip'                 => '/.*calldrip\.com.*/i',
    'mpulsesoftware'           => '/.*mpulse\.net.*/i',
    'demdex'                   => '/.*demdex\.net.*/i',
    'netlook'                  => '/.*netlook\.com.*/i',
    'fyusion'                  => '/.*fyu\.se.*/i',
    'crwdcntrl'                => '/.*crwdcntrl\.net.*/i',
    'userway'                  => '/.*userway\.org.*/i',
    'simplifi'                 => '/.*simpli\.fi.*/i',
    'flexiti financial'        => '/.*flexiti\.fi.*/i',
    'pubmatic'                 => '/.*pubmatic\.com.*/i',
    'tapad'                    => '/.*tapad\.com.*/i',
    'tremorhub'                => '/.*tremorhub\.com.*/i',
    'bluekai'                  => '/.*bluekai\.com.*/i',
    'intentiq'                 => '/.*intentiq\.com.*/i',
    'hammertime'               => '/.*hammer\-corp\.com.*/i',
    'msecnd'                   => '/.*msecnd\.net.*/i',
    'cargurus'                 => '/.*cargurus\.com.*/i',
    'carproof'                 => '/.*carproof\.com.*/i',
    'tiqcdn'                   => '/.*tiqcdn\.com.*/i',
    'autofi'                   => '/.*autofi\.com.*/i',
    'podium'                   => '/.*podium\.com.*/i',
    'stripe'                   => '/.*stripe\.com.*/i',
    'dmdt'                     => '/.*dmdt\.io.*/i',
    'optimole'                 => '/.*optimole\.com.*/i',
    'cimpress'                 => '/.*cimpress.*/i',
    'adgear'                   => '/.*adgrx\.com.*/i',
    'zoho'                     => '/.*zoho\.com.*/i',
    'hubspot'                  => '/.*hubspot\.com.*/i',
    'speedycollision'          => '/.*speedycollision\.com.*/i',
    'evidon'                   => '/.*evidon\.com.*/i',
]; // 106