INSERT INTO ad_details (campaign,tag,dealership,make,model,`year`,trim,entryType,value,ad_type) VALUES
-- smedia_goldenvalley_cadillac_new_make_dealership #LowFunnelBrandWhereToBuy
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','[make] Dealer [city(1)]','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Get The Best Deals With Us','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','View Inventory, Prices, Offers','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Attractive Finance Offers','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','Get the Best Deals','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h','5-Star Customer Service','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','d','Get current offers, rates & promotions. New models in stock.','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','d','Get the best deals and selection on new models at [company_name] in [city].','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [year] [make].','rsa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h1','[make] Dealer [city(1)]','esa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on new [make] models.','esa'),
('smedia_new_make','LowFunnelBrandWhereToBuy','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa'),

-- smedia_goldenvalley_cadillac_new_make_model_year #HighFunnelModelResearch

('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h','[year(1)] [make(2)] [model]','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h','Starting at [price]','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h','Shop [model] Inventory','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h','[year] [model] in Stock','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','d','[model] in stock.','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','d','[year] [model] for sale at [company_name] in [city].','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [make] [model].','rsa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h1','[year] [model] for Sale','esa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on this [year] [make] [model]','esa'),
('smedia_new_make_model_year','HighFunnelModelResearch','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa'),

-- smedia_goldenvalley_cadillac_new_make_model_year #LowFunnelModelWhereToBuy
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','[year] [make] [model]','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','Starting at [price]','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','Shop [model] Inventory','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','[year] [model] in Stock','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','Attractive Finance Offers','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','Get the Best Deals','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h','5-Star Customer Service','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','d','[model] in stock.','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','d','[year] [model] for sale at [company_name] in [city].','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [make] [model].','rsa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h1','[year] [model] for Sale','esa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on this [year] [make] [model]','esa'),
('smedia_new_make_model_year','LowFunnelModelWhereToBuy','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa'),
-- smedia_goldenvalley_cadillac_new_make_model_year #MidFunnelModelAffordability
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','[year(1)] [make(2)] [model]','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','Starting at [price]','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','Shop [model] Inventory','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','[year] [model] in Stock','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','Attractive Finance Offers','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','Get the Best Deals','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h','5-Star Customer Service','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','d','[model] in stock.','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','d','[year] [model] for sale at [company_name] in [city].','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [make] [model].','rsa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h1','[year] [model] for Sale','esa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on this [year] [make] [model]','esa'),
('smedia_new_make_model_year','MidFunnelModelAffordability','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa'),

-- smedia_goldenvalley_cadillac_new_make_model_year #MidFunnelModelDeals
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','[year(1)] [make(2)] [model]','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','Starting at [price]','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','Shop [model] Inventory','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','[year] [model] in Stock','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','Attractive Finance Offers','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','Get the Best Deals','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h','5-Star Customer Service','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','d','[model] in stock.','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','d','[year] [model] for sale at [company_name] in [city].','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [make] [model].','rsa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h1','[year] [model] for Sale','esa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on this [year] [make] [model]','esa'),
('smedia_new_make_model_year','MidFunnelModelDeals','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa'),


-- smedia_goldenvalley_cadillac_new_make_bodystyle_year #HighFunnelBodystyleResearch
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','[year(1)] [make(2)] [body_style]','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','Starting at [price]','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','View Inventory, Prices, Offers','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','Attractive Finance Offers','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','Get the Best Deals','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h','5-Star Customer Service','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','d','In stock. Get current offers, rates & promotions.','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','d','[year] models for sale at [company_name] in [city].','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [year] [make].','rsa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h1','[year] [make] [body_style]','esa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on [year] [make] [body_style].','esa'),
('smedia_new_make_bodystyle_year','HighFunnelBodystyleResearch','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa'),

-- smedia_goldenvalley_cadillac_new_make_year #HighFunnelBrandResearch
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','[year] [make] for Sale','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','Starting at [price]','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','View Inventory, Prices, Offers','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','Book a Test Drive','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','Attractive Finance Offers','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','Get the Best Deals','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h','5-Star Customer Service','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','d','In stock. Get current offers, rates & promotions.','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','d','[year] models for sale at [company_name] in [city].','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','d','Shop our inventory of the new [year] [make].','rsa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','d','[company_name] is committed to our customers. Call, text or chat today.','rsa'),

('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h1','[year] [make] for Sale','esa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h2','Test Drives Delivered to you','esa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','h3','[company_name]','esa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','d1','Get pricing & financing info on this [year] [make].','esa'),
('smedia_new_make_year','HighFunnelBrandResearch','goldenvalley_cadillac','','','','','d2','Shop online & we will bring the vehicle to you. Buy Happy from Home.','esa');
