-- audilacrosse
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','audilacrosse','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','audilacrosse','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','audilacrosse','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','audilacrosse','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','audilacrosse','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','audilacrosse','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','audilacrosse','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- brenengenkiacom
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','brenengenkiacom','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','brenengenkiacom','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','brenengenkiacom','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','brenengenkiacom','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','brenengenkiacom','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','brenengenkiacom','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','brenengenkiacom','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- brooklynparksubaru
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','brooklynparksubaru','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','brooklynparksubaru','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','brooklynparksubaru','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','brooklynparksubaru','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','brooklynparksubaru','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','brooklynparksubaru','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','brooklynparksubaru','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- minnetonkaford
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','minnetonkaford','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','minnetonkaford','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','minnetonkaford','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkaford','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkaford','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkaford','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkaford','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- minnetonkasubaru
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','minnetonkasubaru','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','minnetonkasubaru','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','minnetonkasubaru','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkasubaru','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkasubaru','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkasubaru','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','minnetonkasubaru','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- morriesbuffaloford
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','morriesbuffaloford','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','morriesbuffaloford','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','morriesbuffaloford','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','morriesbuffaloford','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','morriesbuffaloford','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','morriesbuffaloford','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','morriesbuffaloford','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- morries394hyundai
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','morries394hyundai','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','morries394hyundai','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','morries394hyundai','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','morries394hyundai','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','morries394hyundai','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','morries394hyundai','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','morries394hyundai','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- morries
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','morries','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','morries','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','morries','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','morries','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','morries','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','morries','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','morries','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- vwlacrosse
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','vwlacrosse','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','vwlacrosse','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','vwlacrosse','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','vwlacrosse','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','vwlacrosse','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','vwlacrosse','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','vwlacrosse','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);

-- westendlincoln
INSERT INTO spidri_ads.tbl_ad_special_campaigns (stock_type,dealership,`structure`,field_map,`type`,service,tag,car_filters,value_map) VALUES
	 ('new','westendlincoln','make','','generic','adwords','LowFunnelBrandWhereToBuy','',NULL),
	 ('new','westendlincoln','make_bodystyle_year','{"bodystyle": "body_style"}','generic','adwords','HighFunnelBodystyleResearch','{"year": [2020, 2021]}','{"body_style":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"},"bodystyle":{"4D Sedan":"Cars","Cars":"Cars","4D Sport Utility":"SUVs","SUV":"SUVs","3D Cargo Van":"Vans","4D Passenger Van":"Vans","3D Extended Cargo Van":"Vans","3D Medium Roof Cargo Van":"Vans","Passenger Van":"Vans","2D Convertible":"Convertible","2D Coupe":"Coupe","4D Hatchback":"Compact","4D Crew Cab":"Trucks","4D Double Cab":"Trucks","Super Cab":"Trucks","2D Standard Cab":"Trucks","courtesy-loaner":"courtesy-loaner","4D Wagon":"4D Wagon","ROADSTER":"ROADSTER","Compact":"Compact","5D Wagon":"5D Wagon","4D SuperCrew":"4D SuperCrew"}}'),
	 ('new','westendlincoln','make_model_year','','generic','adwords','HighFunnelModelResearch','{"year": [2020, 2021]}',NULL),
	 ('new','westendlincoln','make_model_year','','generic','adwords','MidFunnelModelAffordability','{"year": [2020, 2021]}',NULL),
	 ('new','westendlincoln','make_model_year','','generic','adwords','MidFunnelModelDeals','{"year": [2020, 2021]}',NULL),
	 ('new','westendlincoln','make_model_year','','generic','adwords','LowFunnelModelWhereToBuy','{"year": [2020, 2021]}',NULL),
	 ('new','westendlincoln','make_year','','generic','adwords','HighFunnelBrandResearch','{"year": [2020, 2021]}',NULL);
