INSERT INTO ad_details (campaign,tag,dealership,make,model,`year`,trim,entryType,value,ad_type) VALUES
-- new_make
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','New [year] [make] Models','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on New [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [company_name]','rsa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make

('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h1','New [make] Cars for Sale','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d1','Explore Our Full [make] Range to Find Your Perfect Car and Take One for A Test Drive','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name]','esa'),

('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h1','Shop New [make] Cars','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] Inventory','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h1','New [year] [make] Models','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On New [make] Models. Call Now and Book A Test Drive','esa'),
('smedia_new_make','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),

-- new_make_bodystyle -- special

('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','New [make] [body_style]','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on New [make] [body_style]. Get in Touch with Us','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [dealership]','rsa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_bodystyle

('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h1','New [make] [body_style] for Sale','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d1','Explore Our Full [make] Range to Find Your Perfect Car and Take One for A Test Drive. ','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [dealership].','esa'),

('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h1','New [year] [make] [body_style]','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h3','[dealership]','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] [body_style].','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h1','New [make] [body_style] Models','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On New [make] [body_style]. Call Now and Book A Test Drive','esa'),
('smedia_new_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),


-- new_make_model
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','New [make] [model]','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on The New [make] [model]','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d','Explore the [year] [make] [model]. Find Your Perfect Car & Take One for A Test Drive','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [company_name]','rsa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_model
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h1','New [make] [model]','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d1','Explore the [year] [make] [model]. Find Your Perfect Car & Take One for A Test Drive','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h1','[make] [model] for Sale','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d1','Test Drive the New [make] [model]','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d2','Explore Our Full Range. Get the Best Deal With Us','esa'),

('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h1','New [make] [model]','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d1','Get Current Offers, Pricing and Exclusive Financing Deals on The New [make] [model]','esa'),
('smedia_new_make_model','Research','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive Today and Experience the Thrill of Driving Your Dream Car!','esa'),

-- new_make_model_trim special
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','New [make] [model] [trim]','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on The New [model] [trim]','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Explore the [make] [model] [trim]. Find Your Perfect Car & Take One for A Test Drive','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [company_name]','rsa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_model_trim
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h1','New [make] [model] [trim]','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d1','Explore the [make] [model] [trim]. Find Your Perfect Car & Take One for A Test Drive','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h1','[make] [model] [trim] for Sale','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d1','Test Drive the New [make] [model]','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d2','Explore Our Full Range. Get the Best Deal With Us','esa'),

('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h1','New [make] [model] [trim]','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d1','Get Current Offers, Prices & Exclusive Finance Deals on The New [make] [model] [trim]','esa'),
('smedia_new_make_model_trim','Research','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive Today and Experience the Thrill of Driving Your Dream Car!','esa'),

-- new_make_year -- special
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','New [year] [make] Models','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on New [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [company_name]','rsa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_year
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h1','New [year] [make] Models','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d1','Explore Our [year] [make] Range to Find Your Perfect Car and Take One for A Test Drive','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name]','esa'),

('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h1','Shop New [year] [make]','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] Inventory','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h1','All New [make] [year]','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On New [make] Models. Call Now and Book A Test Drive','esa'),
('smedia_new_make_year','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),

-- new_make_bodystyle_year --special
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','[year] [make] [body_style]','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on New [make] [body_style]. Get in Touch with Us','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New [year] Models at [company_name]','rsa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_bodystyle_year
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h1','[year] [make] [body_style] for Sale','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d1','Explore Our Full [make] Range to Find Your Perfect Car and Take One for A Test Drive','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name]','esa'),

('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h1','[make] [body_style] [year]','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] [body_style]','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h1','[year] [make] [body_style]','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On New [make] [body_style]. Call Now and Book A Test Drive','esa'),
('smedia_new_make_bodystyle_year','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),

-- new_make_model_year_trim
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','[year] [make] [model] [trim]','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on The New [model] [trim]','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Explore the [year] [model] [trim]. Find Your Perfect Car & Take One for A Test Drive','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [company_name]','rsa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_model_year_trim
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h1','[year] [make] [model] [trim]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d1','Explore the [year] [make] [model]. Find Your Perfect Car & Take One for A Test Drive','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h1','[make] [model] [trim] [year]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d1','Test Drive the New [make] [model]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d2','Explore Our Full Range. Get the Best Deal With Us','esa'),

('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h1','[year] [make] [model] [trim]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d1','Get Current Offers, Prices & Exclusive Finance Deals on The New [make] [model] [trim]','esa'),
('smedia_new_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive Today and Experience the Thrill of Driving Your Dream Car!','esa'),

-- new_make_model_year
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','New [year] [make] [model]','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on The New [make] [model]','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Explore the [year] [make] [model]. Find Your Perfect Car & Take One for A Test Drive','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection On New Models at [company_name]','rsa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- new_make_model_year
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h1','New [year] [make] [model]','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d1','Explore the [year] [make] [model]. Find Your Perfect Car & Take One for A Test Drive','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h1','[year] [make] [model] for Sale','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d1','Test Drive the New [make] [model]','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d2','Explore Our Full Range. Get the Best Deal With Us','esa'),

('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h1','New [make] [model] [year]','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d1','Get Current Offers, Pricing and Exclusive Financing Deals on The New [make] [model]','esa'),
('smedia_new_make_model_year','Research','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive Today and Experience the Thrill of Driving Your Dream Car!','esa'),

-- used_make
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Used [make] Cars','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on Used [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h1','Used [make] Cars for Sale','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d1','Explore Our Pre-Owned [make] Range to Find Your Perfect Car. Schedule A Test Drive.','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h1','Shop Used [make] Cars','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] Inventory','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [make] Models','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [make] Cars. Call Now and Book A Test Drive','esa'),
('smedia_used_make','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),

-- used_make_bodystyle -- special
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Used [make] [body_style]','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on Used [make] [body_style]. Get in Touch with Us','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make_bodystyle
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [body_style] for Sale','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d1','Explore Our Pre-Owned [make] Range to Find Your Perfect Car. Schedule A Test Drive.','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [body_style]','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] [body_style]','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [make] [body_style]','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [make] [body_style]. Book Your Test Drive Today','esa'),
('smedia_used_make_bodystyle','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),

-- used_make_model
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Used [make] [model]','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on Used [make] [model]','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make_model
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [model]','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d1','Pre-Owned [make] [model] Starting at [price]. Don''t Miss Out On Our Incredible Offers.','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d2','Get the Best Deals and Selection at [company_name].','esa'),

('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [model] for Sale','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d1','Certified Pre-Owned Vehicles. Book a Test Drive Today.','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d2','Get the Best Deals With Us!','esa'),

('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [make] [model]','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [make] [model]. Explore Our Range Today','esa'),
('smedia_used_make_model','Research','mercedesbenzofstpaul','','','','','d2','Book a Test Drive At Home or At Our Dealership!','esa'),

-- used_make_model_trim -- special
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Used [make] [model] [trim]','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on Used [model] [trim]','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make_model_trim
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [model] [trim]','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d1','Pre-Owned [make] [model] Starting at [price]. Don''t Miss Out On Our Incredible Offers.','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d2','Get the Best Deals and Selection at [company_name].','esa'),

('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [model] [trim]','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d1','Certified Pre-Owned Vehicles. Book a Test Drive Today.','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d2','Get the Best Deals With Us!','esa'),

('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [make] [model]','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [make] [model]. Explore Our Range Today','esa'),
('smedia_used_make_model_trim','Research','mercedesbenzofstpaul','','','','','d2','Book a Test Drive At Home or At Our Dealership!','esa'),

-- used_make_year -- special
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Used [year] [make] Cars','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on Used [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make_year
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h1','Used [year] [make] Cars','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d1','Explore Our Pre-Owned [make] Range to Find Your Perfect Car. Schedule A Test Drive.','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d2','Get the Latest Deals and Best Selection at [company_name].','esa'),

('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h1','Used [make] [year]','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h2','At-Home Test Drives. Book Now','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d1','Great Selection of [make] Inventory','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d2','View Prices, Deals & Customize Your Financing Plan','esa'),

('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [year] [make]','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h2','Starting from [price]','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','h3','Find Your Model, Colour, Trim','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [make] Cars. Call Now and Book A Test Drive','esa'),
('smedia_used_make_year','Research','mercedesbenzofstpaul','','','','','d2','Check Out Our Exclusive Offers & Finance Deals!','esa'),

-- used_make_model_year
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Enabled','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Used [year] [make] [model]','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on Used [make] [model]','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make_model_year
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h1','Used [year] [make] [model]','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d1','Pre-Owned [make] [model] Starting at [price]. Don''t Miss Out On Our Incredible Offers.','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d2','Get the Best Deals and Selection at [company_name].','esa'),

('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h1','Used [year] [make] [model]','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d1','Certified Pre-Owned Vehicles','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d2','Book a Test Drive Today. Get the Best Deals With Us!','esa'),

('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [make] [model]','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [year] [make] [model]. Explore Our Range Today','esa'),
('smedia_used_make_model_year','Research','mercedesbenzofstpaul','','','','','d2','Book a Test Drive At Home or At Our Dealership!','esa'),

-- used_make_model_year_trim
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Enabled','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Used [year] [model] [trim]','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Starting from [price]','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Explore Our Full Range','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h','Easy Financing Options','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Get Current Offers, Pricing and Exclusive Financing Deals on Used [model] [trim]','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Get the Latest Deals and Best Selection on Pre-Owned Vehicles at [company_name]','rsa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Finance Payments.','rsa'),

-- used_make_model_year_trim
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [model] [trim]','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h2','See Inventory, Prices & Offers','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d1','Used [year] [make] [model] Starting at [price]. Don''t Miss Out On Our Incredible Offers','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d2','Get the Best Deals and Selection at [company_name].','esa'),

('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h1','Used [year] [model] [trim]','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h3','See Inventory, Specs & Prices','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d1','Certified Pre-Owned Vehicles.','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d2','Book a Test Drive Today. Get the Best Deals With Us!','esa'),

('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h1','Pre-Owned [year] [model]','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h2','Starting at [price]','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d1','Get the Most Competitive Price On Used [make] [model] [trim]. Explore Our Range Today','esa'),
('smedia_used_make_model_year_trim','Research','mercedesbenzofstpaul','','','','','d2','Book a Test Drive At Home or At Our Dealership!','esa'),

-- new_make #lease
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','[make] Lease Specials','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Explore Our Full Lineup','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h','Explore Your Options Now','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','rsa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Payment Plan!','rsa'),

-- new_make #lease
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h1','[make] Lease Specials','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h2','Explore Your Options Now','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h3','Get Pricing & Detailed Info','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d1','Get Behind the Wheel of Your Dream Car at A Great Price. Schedule A Test Drive!','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d2','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','esa'),

('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h1','Lease a New [make]','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h2','Get the Best Deals With Us','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d1','Get Current Offers, Pricing and Exclusive Lease and Financing Deals Today.','esa'),
('smedia_new_make','ResearchLease','mercedesbenzofstpaul','','','','','d2','Explore Our Full Range to Find Your Perfect Car and Take One for A Test Drive.','esa'),

-- new_make_model #lease
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','[make] [model] Lease','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Offers','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Explore Our Full Lineup','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Special Offers & Incentives','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h','Explore Your Options Now','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on [make] [model]. Get in Touch with Us','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','rsa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Payment Plan!','rsa'),

-- new_make_model #lease
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h1','[make] [model] Lease','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h2','Explore Your Options Now','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h3','Get Pricing & Detailed Info','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d1','Get Behind the Wheel of Your Dream Car at A Great Price. Schedule A Test Drive!','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d2','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','esa'),

('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h1','Lease a [make] [model]','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h2','Get the Best Deals With Us','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d1','Get Into Your New [make] [model] Today. See Current Offers, Pricing and Deals.','esa'),
('smedia_new_make_model','ResearchLease','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive and Experience the Thrill of Driving Your Dream Car!','esa'),


-- new_make #offer
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Attractive [make] Offers','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Photos','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Explore Our Full Lineup','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h','Explore Your Options Now','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','rsa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Payment Plan!','rsa'),

-- new_make #offer
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h1','Attractive [make] Deals','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h2','New Models in Stock Now','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h3','Get Pricing & Detailed Info','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d1','Get Behind the Wheel of Your Dream Car at A Great Price. Schedule A Test Drive!','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d2','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','esa'),

('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h1','[year] [make] Offers','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h2','See Lease & Finance Specials','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d1','Get Into Your New [make] Today. Explore Our Full Range. Check Out Our Current Offers','esa'),
('smedia_new_make','ResearchOffer','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive and Experience the Thrill of Driving Your Dream Car!','esa'),

-- new_make_modle #offer
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','[make] [model] Offers','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Photos','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Explore Our Full Lineup','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h','Explore Your Options Now','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on [make] [model]. Get in Touch with Us','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','rsa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Payment Plan!','rsa'),

-- new_make_modle #offer
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h1','[make] [model] Offers','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h2','Get Pricing & Detailed Info','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d1','Get Behind the Wheel of Your Dream Car at A Great Price. Schedule A Test Drive!','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d2','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','esa'),

('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h1','Best [make] [model] Deals','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h2','Customize Your Financing Plan','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d1','Get Into Your New [make] [model] Today. See Current Offers, Pricing and Deals.','esa'),
('smedia_new_make_model','ResearchOffer','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive and Experience the Thrill of Driving Your Dream Car!','esa'),

-- new_make #finance
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','[make] Finance Offers','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Photos','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Explore Our Full Lineup','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Find Your Model, Colour & Trim','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h','Explore Your Options Now','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on [make] Vehicles. Get in Touch with Us','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','rsa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Payment Plan!','rsa'),

-- new_make #finance
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h1','[make] Financing Offers','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h2','New Models in Stock Now','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h3','Get Pricing & Detailed Info','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d1','Get Behind the Wheel of Your Dream Car at A Great Price. Schedule A Test Drive!','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d2','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','esa'),

('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h1','Attractive [make] Deals','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h2','See Lease & Finance Specials','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d1','Get Into Your New [make] Today. Explore Our Full Range. Check Out Our Current Offers','esa'),
('smedia_new_make','ResearchFinance','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive and Experience the Thrill of Driving Your Dream Car!','esa'),

-- new_make_modle #finance
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','[make] [model] Finance','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','See Inventory, Prices & Photos','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Build Your Deal Now','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Schedule a Test Drive','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Explore Our Full Lineup','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Find Your Colour & Trim','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','New & Pre-Owned Car Dealership','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Unparalleled Customer Service','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Get The Best Deals','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h','Explore Your Options Now','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d','Get Current Offers, Rates & Promotions on [make] [model]. Get in Touch with Us','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d','Explore Our Full [make] Lineup to Find Your Perfect Car & Take One for A Test Drive.','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','rsa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d','Check Out Our Inventory, Specs and Photos. Customize Your Monthly Payment Plan!','rsa'),

-- new_make_modle #finance
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h1','[make] [model] Financing','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h2','Get Pricing & Detailed Info','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h3','Unparalleled Customer Service','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d1','Get Behind the Wheel of Your Dream Car at A Great Price. Schedule A Test Drive!','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d2','We Offer Attractive Leasing and Financing Options to Suit Your Needs. Contact Us','esa'),

('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h1','[make] [model] Deals','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h2','See Lease & Finance Specials','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','h3','[company_name]','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d1','Get Into Your New [make] [model] Today. See Current Offers, Pricing and Deals.','esa'),
('smedia_new_make_model','ResearchFinance','mercedesbenzofstpaul','','','','','d2','Schedule a Test Drive and Experience the Thrill of Driving Your Dream Car!','esa');
